In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
ini_df = pd.read_csv("./CIS_662 _INITIAL_Predictions.csv")
ini_df

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late
0,4/10/24,WEDNESDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
1,4/10/24,WEDNESDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
2,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN
3,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
4,4/10/24,WEDNESDAY,WN 5285,MCO,11:05 AM,1:45 PM,NaN,NaN,NaN,NaN
5,4/10/24,WEDNESDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN
6,4/11/24,THURSDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
7,4/11/24,THURSDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
8,4/11/24,THURSDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN
9,4/11/24,THURSDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
10,4/11/24,THURSDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN
11,4/11/24,THURSDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN
12,4/12/24,FRIDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
13,4/12/24,FRIDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
14,4/12/24,FRIDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN
15,4/12/24,FRIDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
16,4/12/24,FRIDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN
17,4/12/24,FRIDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN
18,4/13/24,SATURDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
19,4/13/24,SATURDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
20,4/13/24,SATURDAY,B6 116,JFK,1:12 PM,2:30 PM,NaN,NaN,NaN,NaN
21,4/13/24,SATURDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
22,4/13/24,SATURDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN

In [3]:
ini_df["scheduled_departure_time"] = ini_df["DATE"] + ' ' + ini_df["DEPARTURE TIME"]
ini_df["scheduled_arrival_time"] = ini_df["DATE"] + ' ' + ini_df["ARRIVAL TIME"]
ini_df["Carrier Code"] = ini_df["FLIGHT NUMBER"].apply(lambda x: x.split()[0])

In [4]:
ini_df

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code
0,4/10/24,WEDNESDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,4/10/24 6:52 PM,4/10/24 9:47 PM,UA
1,4/10/24,WEDNESDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,4/10/24 7:59 PM,4/10/24 10:52 PM,AA
2,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,4/10/24 1:33 PM,4/10/24 2:50 PM,B6
3,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,4/10/24 2:55 PM,4/10/24 4:21 PM,DL
4,4/10/24,WEDNESDAY,WN 5285,MCO,11:05 AM,1:45 PM,NaN,NaN,NaN,NaN,4/10/24 11:05 AM,4/10/24 1:45 PM,WN
5,4/10/24,WEDNESDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,4/10/24 1:35 PM,4/10/24 4:25 PM,B6
6,4/11/24,THURSDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,4/11/24 6:52 PM,4/11/24 9:47 PM,UA
7,4/11/24,THURSDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,4/11/24 7:59 PM,4/11/24 10:52 PM,AA
8,4/11/24,THURSDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,4/11/24 1:33 PM,4/11/24 2:50 PM,B6
9,4/11/24,THURSDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,4/11/24 2:55 PM,4/11/24 4:21 PM,DL
10,4/11/24,THURSDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,4/11/24 11:35 AM,4/11/24 2:20 PM,WN
11,4/11/24,THURSDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,4/11/24 1:35 PM,4/11/24 4:25 PM,B6
12,4/12/24,FRIDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,4/12/24 6:52 PM,4/12/24 9:47 PM,UA
13,4/12/24,FRIDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,4/12/24 7:59 PM,4/12/24 10:52 PM,AA
14,4/12/24,FRIDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,4/12/24 1:33 PM,4/12/24 2:50 PM,B6
15,4/12/24,FRIDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,4/12/24 2:55 PM,4/12/24 4:21 PM,DL
16,4/12/24,FRIDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,4/12/24 11:35 AM,4/12/24 2:20 PM,WN
17,4/12/24,FRIDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,4/12/24 1:35 PM,4/12/24 4:25 PM,B6
18,4/13/24,SATURDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,4/13/24 6:52 PM,4/13/24 9:47 PM,UA
19,4/13/24,SATURDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,4/13/24 7:59 PM,4/13/24 10:52 PM,AA
20,4/13/24,SATURDAY,B6 116,JFK,1:12 PM,2:30 PM,NaN,NaN,NaN,NaN,4/13/24 1:12 PM,4/13/24 2:30 PM,B6
21,4/13/24,SATURDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,4/13/24 2:55 PM,4/13/24 4:21 PM,DL
22,4/13/24,SATURDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,4/13/24 1:35 PM,4/13/24 4:25 PM,B6

In [5]:
# ini_df["scheduled_arrival_time"] = pd.to_datetime(ini_df["scheduled_arrival_time"], format="%m/%d/%Y %I:%M %p")
ini_df["scheduled_arrival_time"] = pd.to_datetime(ini_df["scheduled_arrival_time"], infer_datetime_format=True)
ini_df["scheduled_departure_time"] = pd.to_datetime(ini_df["scheduled_departure_time"], infer_datetime_format=True)
ini_df

/var/folders/d0/d8qgs1qn1x5dwdq_9zy4q3rm0000gn/T/ipykernel_57232/435628835.py:2: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  ini_df["scheduled_arrival_time"] = pd.to_datetime(ini_df["scheduled_arrival_time"], infer_datetime_format=True)
/var/folders/d0/d8qgs1qn1x5dwdq_9zy4q3rm0000gn/T/ipykernel_57232/435628835.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ini_df["scheduled_arrival_time"] = pd.to_datetime(ini_df["scheduled_arrival_time"], infer_datetime_format=True)
/var/folders/d0/d8qgs1qn1x5dwdq_9zy4q3rm0000gn/T/ipykernel_57232/435628835.py:3: UserWarning: The argument 'infer_datetime_format' is deprecated and will be removed in a future version. A strict version of it is now the default, see https://pandas.pydata.org/pdeps/0004-consistent-to-datetime-parsing.html. You can safely remove this argument.
  ini_df["scheduled_departure_time"] = pd.to_datetime(ini_df["scheduled_departure_time"], infer_datetime_format=True)
/var/folders/d0/d8qgs1qn1x5dwdq_9zy4q3rm0000gn/T/ipykernel_57232/435628835.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ini_df["scheduled_departure_time"] = pd.to_datetime(ini_df["scheduled_departure_time"], infer_datetime_format=True)

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code
0,4/10/24,WEDNESDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-10 18:52:00,2024-04-10 21:47:00,UA
1,4/10/24,WEDNESDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-10 19:59:00,2024-04-10 22:52:00,AA
2,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-10 13:33:00,2024-04-10 14:50:00,B6
3,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-10 14:55:00,2024-04-10 16:21:00,DL
4,4/10/24,WEDNESDAY,WN 5285,MCO,11:05 AM,1:45 PM,NaN,NaN,NaN,NaN,2024-04-10 11:05:00,2024-04-10 13:45:00,WN
5,4/10/24,WEDNESDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-10 13:35:00,2024-04-10 16:25:00,B6
6,4/11/24,THURSDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-11 18:52:00,2024-04-11 21:47:00,UA
7,4/11/24,THURSDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-11 19:59:00,2024-04-11 22:52:00,AA
8,4/11/24,THURSDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-11 13:33:00,2024-04-11 14:50:00,B6
9,4/11/24,THURSDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-11 14:55:00,2024-04-11 16:21:00,DL
10,4/11/24,THURSDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-11 11:35:00,2024-04-11 14:20:00,WN
11,4/11/24,THURSDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-11 13:35:00,2024-04-11 16:25:00,B6
12,4/12/24,FRIDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-12 18:52:00,2024-04-12 21:47:00,UA
13,4/12/24,FRIDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-12 19:59:00,2024-04-12 22:52:00,AA
14,4/12/24,FRIDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-12 13:33:00,2024-04-12 14:50:00,B6
15,4/12/24,FRIDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-12 14:55:00,2024-04-12 16:21:00,DL
16,4/12/24,FRIDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-12 11:35:00,2024-04-12 14:20:00,WN
17,4/12/24,FRIDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-12 13:35:00,2024-04-12 16:25:00,B6
18,4/13/24,SATURDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-13 18:52:00,2024-04-13 21:47:00,UA
19,4/13/24,SATURDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-13 19:59:00,2024-04-13 22:52:00,AA
20,4/13/24,SATURDAY,B6 116,JFK,1:12 PM,2:30 PM,NaN,NaN,NaN,NaN,2024-04-13 13:12:00,2024-04-13 14:30:00,B6
21,4/13/24,SATURDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-13 14:55:00,2024-04-13 16:21:00,DL
22,4/13/24,SATURDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-13 13:35:00,2024-04-13 16:25:00,B6

In [6]:
wdf = pd.read_csv("./data/modified/weather_bit_jfk_ord_mco_syr.csv")
wdf

,app_temp,azimuth,clouds,dewpt,dhi,dni,elev_angle,ghi,pod,precip_rate,pres,revision_status,rh,slp,snow_rate,solar_rad,temp,timestamp_local,timestamp_utc,ts,uv,vis,weather.description,weather.code,weather.icon,wind_dir,wind_gust_spd,wind_spd,key
0,13.3,308.5,0,7.1,0,0,-81.6,0,n,0.0,1015,final,66,1018,0.0,0,13.3,2020-01-01T00:00:00,2020-01-01T05:00:00,1577854800,0.0,16,Clear Sky,800,c01n,260,3.2,2.10,MCO
1,13.2,245.0,6,7.2,0,0,-81.5,0,n,0.0,1015,final,67,1018,0.0,0,13.2,2020-01-01T00:15:00,2020-01-01T05:15:00,1577855700,0.0,16,Few clouds,801,c02n,265,3.2,2.22,MCO
2,13.1,181.5,12,7.5,0,0,-81.4,0,n,0.0,1014,final,69,1018,0.0,0,13.1,2020-01-01T00:30:00,2020-01-01T05:30:00,1577856600,0.0,16,Few clouds,801,c02n,270,3.2,2.35,MCO
3,12.9,118.0,18,7.6,0,0,-81.2,0,n,0.0,1014,final,70,1018,0.0,0,12.9,2020-01-01T00:45:00,2020-01-01T05:45:00,1577857500,0.0,16,Few clouds,801,c02n,275,3.2,2.47,MCO
4,12.8,54.5,25,7.7,0,0,-81.1,0,n,0.0,1014,final,71,1018,0.0,0,12.8,2020-01-01T01:00:00,2020-01-01T06:00:00,1577858400,0.0,16,Scattered clouds,802,c02n,280,3.2,2.60,MCO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598635,6.2,318.7,0,-1.2,0,0,-30.1,0,n,0.0,1006,interim,56,1021,0.0,0,7.0,2024-04-07T22:45:00,2024-04-08T02:45:00,1712544300,0.0,16,Clear Sky,800,c01n,20,1.6,1.54,SYR
598636,6.9,322.3,42,-2.2,0,0,-32.0,0,n,0.0,1006,interim,52,1022,0.0,0,7.0,2024-04-07T23:00:00,2024-04-08T03:00:00,1712545200,0.0,16,Broken clouds,803,c03n,0,1.0,1.00,SYR
598637,5.0,326.5,42,-4.2,0,0,-33.3,0,n,0.0,1006,interim,48,1022,0.0,0,6.0,2024-04-07T23:15:00,2024-04-08T03:15:00,1712546100,0.0,16,Broken clouds,803,c03n,210,1.6,1.54,SYR
598638,5.8,330.7,42,-2.1,0,0,-34.7,0,n,0.0,1007,interim,56,1022,0.0,0,6.0,2024-04-07T23:30:00,2024-04-08T03:30:00,1712547000,0.0,16,Broken clouds,803,c03n,0,1.0,1.00,SYR
598639,3.6,334.9,42,-4.0,0,0,-36.0,0,n,0.0,1007,interim,56,1022,0.0,0,4.0,2024-04-07T23:45:00,2024-04-08T03:45:00,1712547900,0.0,16,Broken clouds,803,c03n,0,1.0,1.00,SYR

In [7]:
# weather_factors = ['app_temp',
#  'dewpt',
#  'precip_rate',
#  'rh',
#  'temp',
#  'uv',
#  'vis',
#  'weather.code',
#  'wind_gust_spd',
#  'wind_spd',
#  'timestamp_local',
#  'snow_rate',
#  'key'
#  ]

# weather_factors = ['app_temp', 'clouds', 'dewpt', 'pres', 'rh', 
#        'temp', 'timestamp_local', 'uv', 'vis','weather.code', 'wind_dir', 'wind_gust_spd', 'wind_spd']

In [8]:
syr_df = pd.read_csv("./data/modified/SYR_weather_data_forecast_i.csv")
jfk_df = pd.read_csv("./data/modified/JFK_weather_data_forecast_i.csv")
mco_df = pd.read_csv("./data/modified/MCO_weather_data_forecast_i.csv")
ord_df = pd.read_csv("./data/modified/ORD_weather_data_forecast_i.csv")

weather_factors = ['app_temp', 'clouds', 'dewpt', 'pres', 'rh', 'temp', 'timestamp_local', 'uv', 'vis','weather.code', 'wind_dir', 'wind_gust_spd', 'wind_spd']

In [9]:
wdf[weather_factors]

,app_temp,clouds,dewpt,pres,rh,temp,timestamp_local,uv,vis,weather.code,wind_dir,wind_gust_spd,wind_spd
0,13.3,0,7.1,1015,66,13.3,2020-01-01T00:00:00,0.0,16,800,260,3.2,2.10
1,13.2,6,7.2,1015,67,13.2,2020-01-01T00:15:00,0.0,16,801,265,3.2,2.22
2,13.1,12,7.5,1014,69,13.1,2020-01-01T00:30:00,0.0,16,801,270,3.2,2.35
3,12.9,18,7.6,1014,70,12.9,2020-01-01T00:45:00,0.0,16,801,275,3.2,2.47
4,12.8,25,7.7,1014,71,12.8,2020-01-01T01:00:00,0.0,16,802,280,3.2,2.60
...,...,...,...,...,...,...,...,...,...,...,...,...,...
598635,6.2,0,-1.2,1006,56,7.0,2024-04-07T22:45:00,0.0,16,800,20,1.6,1.54
598636,6.9,42,-2.2,1006,52,7.0,2024-04-07T23:00:00,0.0,16,803,0,1.0,1.00
598637,5.0,42,-4.2,1006,48,6.0,2024-04-07T23:15:00,0.0,16,803,210,1.6,1.54
598638,5.8,42,-2.1,1007,56,6.0,2024-04-07T23:30:00,0.0,16,803,0,1.0,1.00
598639,3.6,42,-4.0,1007,56,4.0,2024-04-07T23:45:00,0.0,16,803,0,1.0,1.00

In [10]:
syr_df["timestamp_local"] == pd.to_datetime(syr_df["timestamp_local"])
jfk_df["timestamp_local"] == pd.to_datetime(jfk_df["timestamp_local"])
mco_df["timestamp_local"] == pd.to_datetime(mco_df["timestamp_local"])
ord_df["timestamp_local"] == pd.to_datetime(ord_df["timestamp_local"])
syr_df = syr_df[weather_factors].sort_values("timestamp_local")
jfk_df = jfk_df[weather_factors].sort_values("timestamp_local")
mco_df = mco_df[weather_factors].sort_values("timestamp_local")
ord_df = ord_df[weather_factors].sort_values("timestamp_local")
# syr_df

In [11]:

syr_df

,app_temp,clouds,dewpt,pres,rh,temp,timestamp_local,uv,vis,weather.code,wind_dir,wind_gust_spd,wind_spd
0,16.7,58,5.0,1003.0,46,16.7,2024-04-08T21:00:00,0.0,42.176,803,160,3.60,2.40
1,11.5,30,1.4,1003.0,50,11.5,2024-04-08T22:00:00,0.0,37.184,802,180,3.20,2.40
2,10.7,22,2.3,1003.0,56,10.7,2024-04-08T23:00:00,0.0,35.072,802,180,3.20,2.40
3,9.9,18,2.0,1002.5,58,9.9,2024-04-09T00:00:00,0.0,34.080,801,170,3.20,2.40
4,9.2,13,2.5,1002.0,63,9.2,2024-04-09T01:00:00,0.0,30.992,801,160,3.20,2.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,15.1,72,0.5,994.0,37,15.1,2024-04-15T16:00:00,4.7,24.128,521,274,8.43,6.69
164,14.7,71,0.2,994.0,37,14.7,2024-04-15T17:00:00,2.6,24.128,521,279,8.09,6.17
165,14.2,70,0.1,994.3,38,14.2,2024-04-15T18:00:00,2.2,24.128,521,283,7.33,5.14
166,13.3,68,0.0,994.7,40,13.3,2024-04-15T19:00:00,1.8,24.128,802,288,6.58,4.63
167,12.8,66,-0.1,995.0,41,12.8,2024-04-15T20:00:00,0.0,24.128,802,290,5.82,3.60

In [12]:
ini_df[ini_df["ORIGIN"]=="JFK"]

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code
2,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-10 13:33:00,2024-04-10 14:50:00,B6
3,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-10 14:55:00,2024-04-10 16:21:00,DL
8,4/11/24,THURSDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-11 13:33:00,2024-04-11 14:50:00,B6
9,4/11/24,THURSDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-11 14:55:00,2024-04-11 16:21:00,DL
14,4/12/24,FRIDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-12 13:33:00,2024-04-12 14:50:00,B6
15,4/12/24,FRIDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-12 14:55:00,2024-04-12 16:21:00,DL
20,4/13/24,SATURDAY,B6 116,JFK,1:12 PM,2:30 PM,NaN,NaN,NaN,NaN,2024-04-13 13:12:00,2024-04-13 14:30:00,B6
21,4/13/24,SATURDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-13 14:55:00,2024-04-13 16:21:00,DL

In [13]:
# syr_df["date_time_map"] = pd.to_datetime(syr_df["date_time"], utc=True).dt.tz_convert('America/New_York')
# arrivals_df["date_time"] = arrivals_df["scheduled_arrival_time"].dt.tz_localize('America/New_York', ambiguous='naive')
syr_df["date_time_map"] = pd.to_datetime(syr_df["timestamp_local"])
jfk_df["date_time_map"] = pd.to_datetime(jfk_df["timestamp_local"])
mco_df["date_time_map"] = pd.to_datetime(mco_df["timestamp_local"])
ord_df["date_time_map"] = pd.to_datetime(ord_df["timestamp_local"])
syr_df
jfk_df
mco_df
ord_df

,app_temp,clouds,dewpt,pres,rh,temp,timestamp_local,uv,vis,weather.code,wind_dir,wind_gust_spd,wind_spd,date_time_map
0,18.8,6,8.5,988.0,49,19.5,2024-04-08T20:00:00,0.0,40.480,801,190,4.80,3.20,2024-04-08 20:00:00
1,16.3,17,6.1,989.5,51,16.3,2024-04-08T21:00:00,0.0,37.088,801,190,6.00,4.00,2024-04-08 21:00:00
2,15.5,53,5.4,989.0,51,15.5,2024-04-08T22:00:00,0.0,0.465,803,190,6.00,4.00,2024-04-08 22:00:00
3,14.7,20,5.2,989.0,53,14.7,2024-04-08T23:00:00,0.0,43.072,801,190,6.00,4.00,2024-04-08 23:00:00
4,14.0,53,5.3,988.5,56,14.0,2024-04-09T00:00:00,0.0,37.888,803,190,5.20,3.60,2024-04-09 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163,19.6,63,6.5,987.7,40,20.5,2024-04-15T15:00:00,6.2,24.128,802,128,7.04,5.14,2024-04-15 15:00:00
164,19.0,64,6.3,987.5,41,19.9,2024-04-15T16:00:00,3.5,24.128,802,133,6.80,5.14,2024-04-15 16:00:00
165,17.5,66,6.3,988.0,45,18.4,2024-04-15T17:00:00,2.9,24.128,802,109,6.44,5.14,2024-04-15 17:00:00
166,16.6,81,6.4,988.5,51,16.6,2024-04-15T18:00:00,2.0,24.128,802,117,6.08,5.14,2024-04-15 18:00:00
167,18.2,69,6.7,989.0,47,18.2,2024-04-15T19:00:00,1.3,24.128,802,111,5.72,5.14,2024-04-15 19:00:00

In [17]:
# print(weather_df.shape)
print(jfk_df.shape)
print(mco_df.shape)
print(ord_df.shape)
print(syr_df.shape)

(168, 14)
(168, 14)
(168, 14)
(168, 14)

In [18]:
ini_df["date_time"] = pd.to_datetime(ini_df["scheduled_arrival_time"])
ini_df

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code,date_time
0,4/10/24,WEDNESDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-10 18:52:00,2024-04-10 21:47:00,UA,2024-04-10 21:47:00
1,4/10/24,WEDNESDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-10 19:59:00,2024-04-10 22:52:00,AA,2024-04-10 22:52:00
2,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-10 13:33:00,2024-04-10 14:50:00,B6,2024-04-10 14:50:00
3,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-10 14:55:00,2024-04-10 16:21:00,DL,2024-04-10 16:21:00
4,4/10/24,WEDNESDAY,WN 5285,MCO,11:05 AM,1:45 PM,NaN,NaN,NaN,NaN,2024-04-10 11:05:00,2024-04-10 13:45:00,WN,2024-04-10 13:45:00
5,4/10/24,WEDNESDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-10 13:35:00,2024-04-10 16:25:00,B6,2024-04-10 16:25:00
6,4/11/24,THURSDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-11 18:52:00,2024-04-11 21:47:00,UA,2024-04-11 21:47:00
7,4/11/24,THURSDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-11 19:59:00,2024-04-11 22:52:00,AA,2024-04-11 22:52:00
8,4/11/24,THURSDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-11 13:33:00,2024-04-11 14:50:00,B6,2024-04-11 14:50:00
9,4/11/24,THURSDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-11 14:55:00,2024-04-11 16:21:00,DL,2024-04-11 16:21:00
10,4/11/24,THURSDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-11 11:35:00,2024-04-11 14:20:00,WN,2024-04-11 14:20:00
11,4/11/24,THURSDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-11 13:35:00,2024-04-11 16:25:00,B6,2024-04-11 16:25:00
12,4/12/24,FRIDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-12 18:52:00,2024-04-12 21:47:00,UA,2024-04-12 21:47:00
13,4/12/24,FRIDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-12 19:59:00,2024-04-12 22:52:00,AA,2024-04-12 22:52:00
14,4/12/24,FRIDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-12 13:33:00,2024-04-12 14:50:00,B6,2024-04-12 14:50:00
15,4/12/24,FRIDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-12 14:55:00,2024-04-12 16:21:00,DL,2024-04-12 16:21:00
16,4/12/24,FRIDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-12 11:35:00,2024-04-12 14:20:00,WN,2024-04-12 14:20:00
17,4/12/24,FRIDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-12 13:35:00,2024-04-12 16:25:00,B6,2024-04-12 16:25:00
18,4/13/24,SATURDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-13 18:52:00,2024-04-13 21:47:00,UA,2024-04-13 21:47:00
19,4/13/24,SATURDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-13 19:59:00,2024-04-13 22:52:00,AA,2024-04-13 22:52:00
20,4/13/24,SATURDAY,B6 116,JFK,1:12 PM,2:30 PM,NaN,NaN,NaN,NaN,2024-04-13 13:12:00,2024-04-13 14:30:00,B6,2024-04-13 14:30:00
21,4/13/24,SATURDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-13 14:55:00,2024-04-13 16:21:00,DL,2024-04-13 16:21:00
22,4/13/24,SATURDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-13 13:35:00,2024-04-13 16:25:00,B6,2024-04-13 16:25:00

In [19]:
syr_df.shape

(168, 14)

In [20]:
syr_w_merged_data = pd.merge_asof(ini_df.sort_values('date_time'),
                                       syr_df.sort_values('date_time_map'),
                                       left_on='date_time', right_on='date_time_map', direction='nearest')

syr_w_merged_data.head()

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code,date_time,app_temp,clouds,dewpt,pres,rh,temp,timestamp_local,uv,vis,weather.code,wind_dir,wind_gust_spd,wind_spd,date_time_map
0,4/10/24,WEDNESDAY,WN 5285,MCO,11:05 AM,1:45 PM,NaN,NaN,NaN,NaN,2024-04-10 11:05:00,2024-04-10 13:45:00,WN,2024-04-10 13:45:00,17.2,84,9.4,997.5,60,17.2,2024-04-10T14:00:00,2.9,19.696,804,280,6.90,4.40,2024-04-10 14:00:00
1,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-10 13:33:00,2024-04-10 14:50:00,B6,2024-04-10 14:50:00,17.1,82,9.1,998.0,59,17.1,2024-04-10T15:00:00,2.5,18.720,804,283,6.50,4.26,2024-04-10 15:00:00
2,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-10 14:55:00,2024-04-10 16:21:00,DL,2024-04-10 16:21:00,17.1,80,8.8,998.0,58,17.1,2024-04-10T16:00:00,1.8,24.128,804,286,6.10,4.13,2024-04-10 16:00:00
3,4/10/24,WEDNESDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-10 13:35:00,2024-04-10 16:25:00,B6,2024-04-10 16:25:00,17.1,80,8.8,998.0,58,17.1,2024-04-10T16:00:00,1.8,24.128,804,286,6.10,4.13,2024-04-10 16:00:00
4,4/10/24,WEDNESDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-10 18:52:00,2024-04-10 21:47:00,UA,2024-04-10 21:47:00,12.6,76,6.6,999.0,67,12.6,2024-04-10T22:00:00,0.0,24.128,804,110,4.06,2.53,2024-04-10 22:00:00

In [21]:
# merged_data_time_based["diff"] = (merged_data_time_based["date_time_map"] - merged_data_time_based["date_time"]).dt.total_seconds() / 60
# merged_data_time_based[["date_time", "date_time_map", "Carrier Code", "diff"]]

In [22]:
# syr_df[(syr_df["date_time"]>=pd.Timestamp("2023-09-07", tz="America/New_York")) & (syr_df["date_time"]<pd.Timestamp("2023-09-09", tz="America/New_York"))]

In [23]:
# merged_data_time_based[(merged_data_time_based["diff"]>6) | (merged_data_time_based["diff"]<-6)]

In [24]:

# merged_data_time_based[(merged_data_time_based["diff"]>60) | (merged_data_time_based["diff"]<-60)][["Scheduled Elapsed Time (Minutes)", "Actual Elapsed Time (Minutes)","Arrival Delay (Minutes)", "date_time_x", "date_time_y", "date_time_map", "Carrier Code", "diff"]]

In [25]:
syr_w_merged_data

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code,date_time,app_temp,clouds,dewpt,pres,rh,temp,timestamp_local,uv,vis,weather.code,wind_dir,wind_gust_spd,wind_spd,date_time_map
0,4/10/24,WEDNESDAY,WN 5285,MCO,11:05 AM,1:45 PM,NaN,NaN,NaN,NaN,2024-04-10 11:05:00,2024-04-10 13:45:00,WN,2024-04-10 13:45:00,17.2,84,9.4,997.5,60,17.2,2024-04-10T14:00:00,2.9,19.696,804,280,6.90,4.40,2024-04-10 14:00:00
1,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-10 13:33:00,2024-04-10 14:50:00,B6,2024-04-10 14:50:00,17.1,82,9.1,998.0,59,17.1,2024-04-10T15:00:00,2.5,18.720,804,283,6.50,4.26,2024-04-10 15:00:00
2,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-10 14:55:00,2024-04-10 16:21:00,DL,2024-04-10 16:21:00,17.1,80,8.8,998.0,58,17.1,2024-04-10T16:00:00,1.8,24.128,804,286,6.10,4.13,2024-04-10 16:00:00
3,4/10/24,WEDNESDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-10 13:35:00,2024-04-10 16:25:00,B6,2024-04-10 16:25:00,17.1,80,8.8,998.0,58,17.1,2024-04-10T16:00:00,1.8,24.128,804,286,6.10,4.13,2024-04-10 16:00:00
4,4/10/24,WEDNESDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-10 18:52:00,2024-04-10 21:47:00,UA,2024-04-10 21:47:00,12.6,76,6.6,999.0,67,12.6,2024-04-10T22:00:00,0.0,24.128,804,110,4.06,2.53,2024-04-10 22:00:00
5,4/10/24,WEDNESDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-10 19:59:00,2024-04-10 22:52:00,AA,2024-04-10 22:52:00,11.9,75,6.5,999.0,69,11.9,2024-04-10T23:00:00,0.0,24.128,804,120,4.00,2.40,2024-04-10 23:00:00
6,4/11/24,THURSDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-11 11:35:00,2024-04-11 14:20:00,WN,2024-04-11 14:20:00,18.0,92,11.1,988.5,64,18.0,2024-04-11T14:00:00,2.6,24.128,804,140,16.40,10.80,2024-04-11 14:00:00
7,4/11/24,THURSDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-11 13:33:00,2024-04-11 14:50:00,B6,2024-04-11 14:50:00,18.1,89,10.9,987.5,63,18.1,2024-04-11T15:00:00,2.2,21.472,804,143,17.20,11.33,2024-04-11 15:00:00
8,4/11/24,THURSDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-11 14:55:00,2024-04-11 16:21:00,DL,2024-04-11 16:21:00,18.2,87,11.0,986.0,63,18.2,2024-04-11T16:00:00,1.7,17.024,804,146,18.00,11.86,2024-04-11 16:00:00
9,4/11/24,THURSDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-11 13:35:00,2024-04-11 16:25:00,B6,2024-04-11 16:25:00,18.2,87,11.0,986.0,63,18.2,2024-04-11T16:00:00,1.7,17.024,804,146,18.00,11.86,2024-04-11 16:00:00
10,4/11/24,THURSDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-11 18:52:00,2024-04-11 21:47:00,UA,2024-04-11 21:47:00,17.1,89,11.5,982.0,70,17.1,2024-04-11T22:00:00,0.0,2.856,301,150,16.60,11.06,2024-04-11 22:00:00
11,4/11/24,THURSDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-11 19:59:00,2024-04-11 22:52:00,AA,2024-04-11 22:52:00,17.2,89,11.9,981.5,71,17.2,2024-04-11T23:00:00,0.0,2.718,301,150,16.10,10.80,2024-04-11 23:00:00
12,4/12/24,FRIDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-12 11:35:00,2024-04-12 14:20:00,WN,2024-04-12 14:20:00,14.9,82,7.0,972.5,59,14.9,2024-04-12T14:00:00,3.0,17.456,804,230,14.10,9.67,2024-04-12 14:00:00
13,4/12/24,FRIDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-12 13:33:00,2024-04-12 14:50:00,B6,2024-04-12 14:50:00,14.2,81,6.3,972.5,59,14.2,2024-04-12T15:00:00,2.6,24.128,804,230,14.15,9.63,2024-04-12 15:00:00
14,4/12/24,FRIDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-12 14:55:00,2024-04-12 16:21:00,DL,2024-04-12 16:21:00,13.5,79,5.9,972.0,60,13.5,2024-04-12T16:00:00,1.9,23.952,804,230,14.20,9.60,2024-04-12 16:00:00
15,4/12/24,FRIDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-12 13:35:00,2024-04-12 16:25:00,B6,2024-04-12 16:25:00,13.5,79,5.9,972.0,60,13.5,2024-04-12T16:00:00,1.9,23.952,804,230,14.20,9.60,2024-04-12 16:00:00
16,4/12/24,FRIDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-12 18:52:00,2024-04-12 21:47:00,UA,2024-04-12 21:47:00,9.5,78,3.1,975.0,64,9.5,2024-04-12T22:00:00,0.0,13.568,804,236,14.10,9.40,2024-04-12 22:00:00
17,4/12/24,FRIDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-12 19:59:00,2024-04-12 22:52:00,AA,2024-04-12 22:52:00,8.9,80,3.0,974.5,66,8.9,2024-04-12T23:00:00,0.0,0.130,804,240,13.95,9.36,2024-04-12 23:00:00
18,4/13/24,SATURDAY,B6 116,JFK,1:12 PM,2:30 PM,NaN,NaN,NaN,NaN,2024-04-13 13:12:00,2024-04-13 14:30:00,B6,2024-04-13 14:30:00,8.5,76,1.6,988.0,62,8.5,2024-04-13T14:00:00,3.4,15.120,804,280,15.40,10.27,2024-04-13 14:00:00
19,4/13/24,SATURDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-13 14:55:00,2024-04-13 16:21:00,DL,2024-04-13 16:21:00,8.1,73,1.1,989.0,61,8.1,2024-04-13T16:00:00,2.1,21.125,804,280,15.23,10.11,2024-04-13 16:00:00
20,4/13/24,SATURDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-13 13:35:00,2024-04-13 16:25:00,B6,2024-04-13 16:25:00,8.1,73,1.1,989.0,61,8.1,2024-04-13T16:00:00,2.1,21.125,804,280,15.23,10.11,2024-04-13 16:00:00
21,4/13/24,SATURDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-13 18:52:00,2024-04-13 21:47:00,UA,2024-04-13 21:47:00,3.0,74,1.3,992.7,70,6.4,2024-04-13T22:00:00,0.0,24.128,802,273,11.51,5.14,2024-04-13 22:00:00
22,4/13/24,SATURDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-13 19:59:00,2024-04-13 22:52:00,AA,2024-04-13 22:52:00,2.5,74,1.5,993.0,74,5.8,2024-04-13T23:00:00,0.0,24.128,802,268,9.31,4.63,2024-04-13 23:00:00

In [27]:
jfk_departures_df = syr_w_merged_data[syr_w_merged_data["ORIGIN"]=="JFK"]
# jfk_departures_df = jfk_departures_df[jfk_departures_df["date_time"]>=pd.Timestamp("2020-01-01")].sort_values("date_time").reset_index(drop=True)
jfk_departures_df

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code,date_time,app_temp,clouds,dewpt,pres,rh,temp,timestamp_local,uv,vis,weather.code,wind_dir,wind_gust_spd,wind_spd,date_time_map
1,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-10 13:33:00,2024-04-10 14:50:00,B6,2024-04-10 14:50:00,17.1,82,9.1,998.0,59,17.1,2024-04-10T15:00:00,2.5,18.720,804,283,6.50,4.26,2024-04-10 15:00:00
2,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-10 14:55:00,2024-04-10 16:21:00,DL,2024-04-10 16:21:00,17.1,80,8.8,998.0,58,17.1,2024-04-10T16:00:00,1.8,24.128,804,286,6.10,4.13,2024-04-10 16:00:00
7,4/11/24,THURSDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-11 13:33:00,2024-04-11 14:50:00,B6,2024-04-11 14:50:00,18.1,89,10.9,987.5,63,18.1,2024-04-11T15:00:00,2.2,21.472,804,143,17.20,11.33,2024-04-11 15:00:00
8,4/11/24,THURSDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-11 14:55:00,2024-04-11 16:21:00,DL,2024-04-11 16:21:00,18.2,87,11.0,986.0,63,18.2,2024-04-11T16:00:00,1.7,17.024,804,146,18.00,11.86,2024-04-11 16:00:00
13,4/12/24,FRIDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-12 13:33:00,2024-04-12 14:50:00,B6,2024-04-12 14:50:00,14.2,81,6.3,972.5,59,14.2,2024-04-12T15:00:00,2.6,24.128,804,230,14.15,9.63,2024-04-12 15:00:00
14,4/12/24,FRIDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-12 14:55:00,2024-04-12 16:21:00,DL,2024-04-12 16:21:00,13.5,79,5.9,972.0,60,13.5,2024-04-12T16:00:00,1.9,23.952,804,230,14.20,9.60,2024-04-12 16:00:00
18,4/13/24,SATURDAY,B6 116,JFK,1:12 PM,2:30 PM,NaN,NaN,NaN,NaN,2024-04-13 13:12:00,2024-04-13 14:30:00,B6,2024-04-13 14:30:00,8.5,76,1.6,988.0,62,8.5,2024-04-13T14:00:00,3.4,15.120,804,280,15.40,10.27,2024-04-13 14:00:00
19,4/13/24,SATURDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-13 14:55:00,2024-04-13 16:21:00,DL,2024-04-13 16:21:00,8.1,73,1.1,989.0,61,8.1,2024-04-13T16:00:00,2.1,21.125,804,280,15.23,10.11,2024-04-13 16:00:00

In [28]:
jfk_w_merged_data = pd.merge_asof(jfk_departures_df.sort_values('date_time'),
                                       jfk_df.sort_values('date_time_map'),
                                       left_on='date_time', right_on='date_time_map', direction='nearest')

jfk_w_merged_data.head()

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code,date_time,app_temp_x,clouds_x,dewpt_x,pres_x,rh_x,temp_x,timestamp_local_x,uv_x,vis_x,weather.code_x,wind_dir_x,wind_gust_spd_x,wind_spd_x,date_time_map_x,app_temp_y,clouds_y,dewpt_y,pres_y,rh_y,temp_y,timestamp_local_y,uv_y,vis_y,weather.code_y,wind_dir_y,wind_gust_spd_y,wind_spd_y,date_time_map_y
0,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-10 13:33:00,2024-04-10 14:50:00,B6,2024-04-10 14:50:00,17.1,82,9.1,998.0,59,17.1,2024-04-10T15:00:00,2.5,18.720,804,283,6.50,4.26,2024-04-10 15:00:00,12.3,91,8.2,1015.0,76,12.3,2024-04-10T15:00:00,2.2,24.128,804,93,4.23,3.60,2024-04-10 15:00:00
1,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-10 14:55:00,2024-04-10 16:21:00,DL,2024-04-10 16:21:00,17.1,80,8.8,998.0,58,17.1,2024-04-10T16:00:00,1.8,24.128,804,286,6.10,4.13,2024-04-10 16:00:00,12.3,91,8.2,1015.0,76,12.3,2024-04-10T16:00:00,1.5,24.128,804,96,4.36,3.60,2024-04-10 16:00:00
2,4/11/24,THURSDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-11 13:33:00,2024-04-11 14:50:00,B6,2024-04-11 14:50:00,18.1,89,10.9,987.5,63,18.1,2024-04-11T15:00:00,2.2,21.472,804,143,17.20,11.33,2024-04-11 15:00:00,13.2,95,9.8,1009.0,80,13.2,2024-04-11T15:00:00,2.0,24.128,804,153,12.00,8.00,2024-04-11 15:00:00
3,4/11/24,THURSDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-11 14:55:00,2024-04-11 16:21:00,DL,2024-04-11 16:21:00,18.2,87,11.0,986.0,63,18.2,2024-04-11T16:00:00,1.7,17.024,804,146,18.00,11.86,2024-04-11 16:00:00,13.1,95,9.9,1008.0,81,13.1,2024-04-11T16:00:00,1.4,10.032,804,156,13.20,8.80,2024-04-11 16:00:00
4,4/12/24,FRIDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-12 13:33:00,2024-04-12 14:50:00,B6,2024-04-12 14:50:00,14.2,81,6.3,972.5,59,14.2,2024-04-12T15:00:00,2.6,24.128,804,230,14.15,9.63,2024-04-12 15:00:00,15.6,58,8.6,993.5,63,15.6,2024-04-12T15:00:00,3.5,24.128,803,223,14.95,10.17,2024-04-12 15:00:00

In [29]:
jfk_w_merged_data.shape

(8, 42)

In [30]:
mco_departures_df = syr_w_merged_data[syr_w_merged_data["ORIGIN"]=="MCO"]
# mco_departures_df = mco_departures_df[mco_departures_df["date_time"]>=pd.Timestamp("2020-01-01")].sort_values("date_time").reset_index(drop=True)
mco_departures_df

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code,date_time,app_temp,clouds,dewpt,pres,rh,temp,timestamp_local,uv,vis,weather.code,wind_dir,wind_gust_spd,wind_spd,date_time_map
0,4/10/24,WEDNESDAY,WN 5285,MCO,11:05 AM,1:45 PM,NaN,NaN,NaN,NaN,2024-04-10 11:05:00,2024-04-10 13:45:00,WN,2024-04-10 13:45:00,17.2,84,9.4,997.5,60,17.2,2024-04-10T14:00:00,2.9,19.696,804,280,6.90,4.40,2024-04-10 14:00:00
3,4/10/24,WEDNESDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-10 13:35:00,2024-04-10 16:25:00,B6,2024-04-10 16:25:00,17.1,80,8.8,998.0,58,17.1,2024-04-10T16:00:00,1.8,24.128,804,286,6.10,4.13,2024-04-10 16:00:00
6,4/11/24,THURSDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-11 11:35:00,2024-04-11 14:20:00,WN,2024-04-11 14:20:00,18.0,92,11.1,988.5,64,18.0,2024-04-11T14:00:00,2.6,24.128,804,140,16.40,10.80,2024-04-11 14:00:00
9,4/11/24,THURSDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-11 13:35:00,2024-04-11 16:25:00,B6,2024-04-11 16:25:00,18.2,87,11.0,986.0,63,18.2,2024-04-11T16:00:00,1.7,17.024,804,146,18.00,11.86,2024-04-11 16:00:00
12,4/12/24,FRIDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-12 11:35:00,2024-04-12 14:20:00,WN,2024-04-12 14:20:00,14.9,82,7.0,972.5,59,14.9,2024-04-12T14:00:00,3.0,17.456,804,230,14.10,9.67,2024-04-12 14:00:00
15,4/12/24,FRIDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-12 13:35:00,2024-04-12 16:25:00,B6,2024-04-12 16:25:00,13.5,79,5.9,972.0,60,13.5,2024-04-12T16:00:00,1.9,23.952,804,230,14.20,9.60,2024-04-12 16:00:00
20,4/13/24,SATURDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-13 13:35:00,2024-04-13 16:25:00,B6,2024-04-13 16:25:00,8.1,73,1.1,989.0,61,8.1,2024-04-13T16:00:00,2.1,21.125,804,280,15.23,10.11,2024-04-13 16:00:00

In [31]:
mco_w_merged_data = pd.merge_asof(mco_departures_df.sort_values('date_time'),
                                       mco_df.sort_values('date_time_map'),
                                       left_on='date_time', right_on='date_time_map', direction='nearest')

mco_w_merged_data.head()

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code,date_time,app_temp_x,clouds_x,dewpt_x,pres_x,rh_x,temp_x,timestamp_local_x,uv_x,vis_x,weather.code_x,wind_dir_x,wind_gust_spd_x,wind_spd_x,date_time_map_x,app_temp_y,clouds_y,dewpt_y,pres_y,rh_y,temp_y,timestamp_local_y,uv_y,vis_y,weather.code_y,wind_dir_y,wind_gust_spd_y,wind_spd_y,date_time_map_y
0,4/10/24,WEDNESDAY,WN 5285,MCO,11:05 AM,1:45 PM,NaN,NaN,NaN,NaN,2024-04-10 11:05:00,2024-04-10 13:45:00,WN,2024-04-10 13:45:00,17.2,84,9.4,997.5,60,17.2,2024-04-10T14:00:00,2.9,19.696,804,280,6.9,4.40,2024-04-10 14:00:00,29.1,57,16.4,1013.5,47,28.8,2024-04-10T14:00:00,6.1,35.392,803,150,9.70,6.40,2024-04-10 14:00:00
1,4/10/24,WEDNESDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-10 13:35:00,2024-04-10 16:25:00,B6,2024-04-10 16:25:00,17.1,80,8.8,998.0,58,17.1,2024-04-10T16:00:00,1.8,24.128,804,286,6.1,4.13,2024-04-10 16:00:00,29.6,46,16.0,1009.5,44,29.5,2024-04-10T16:00:00,4.2,24.128,803,143,8.63,5.86,2024-04-10 16:00:00
2,4/11/24,THURSDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-11 11:35:00,2024-04-11 14:20:00,WN,2024-04-11 14:20:00,18.0,92,11.1,988.5,64,18.0,2024-04-11T14:00:00,2.6,24.128,804,140,16.4,10.80,2024-04-11 14:00:00,32.7,57,19.8,1007.0,52,30.8,2024-04-11T14:00:00,6.1,24.128,803,200,19.60,12.80,2024-04-11 14:00:00
3,4/11/24,THURSDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-11 13:35:00,2024-04-11 16:25:00,B6,2024-04-11 16:25:00,18.2,87,11.0,986.0,63,18.2,2024-04-11T16:00:00,1.7,17.024,804,146,18.0,11.86,2024-04-11 16:00:00,31.8,58,19.5,1005.5,53,30.2,2024-04-11T16:00:00,3.7,24.128,202,213,20.13,13.33,2024-04-11 16:00:00
4,4/12/24,FRIDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-12 11:35:00,2024-04-12 14:20:00,WN,2024-04-12 14:20:00,14.9,82,7.0,972.5,59,14.9,2024-04-12T14:00:00,3.0,17.456,804,230,14.1,9.67,2024-04-12 14:00:00,24.9,1,10.0,1016.5,38,25.3,2024-04-12T14:00:00,9.9,24.128,800,300,9.30,6.07,2024-04-12 14:00:00

In [32]:
ord_departures_df = syr_w_merged_data[syr_w_merged_data["ORIGIN"]=="ORD"]
# ord_departures_df = ord_departures_df[ord_departures_df["date_time"]>=pd.Timestamp("2020-01-01")].sort_values("date_time").reset_index(drop=True)
ord_departures_df

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code,date_time,app_temp,clouds,dewpt,pres,rh,temp,timestamp_local,uv,vis,weather.code,wind_dir,wind_gust_spd,wind_spd,date_time_map
4,4/10/24,WEDNESDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-10 18:52:00,2024-04-10 21:47:00,UA,2024-04-10 21:47:00,12.6,76,6.6,999.0,67,12.6,2024-04-10T22:00:00,0.0,24.128,804,110,4.06,2.53,2024-04-10 22:00:00
5,4/10/24,WEDNESDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-10 19:59:00,2024-04-10 22:52:00,AA,2024-04-10 22:52:00,11.9,75,6.5,999.0,69,11.9,2024-04-10T23:00:00,0.0,24.128,804,120,4.00,2.40,2024-04-10 23:00:00
10,4/11/24,THURSDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-11 18:52:00,2024-04-11 21:47:00,UA,2024-04-11 21:47:00,17.1,89,11.5,982.0,70,17.1,2024-04-11T22:00:00,0.0,2.856,301,150,16.60,11.06,2024-04-11 22:00:00
11,4/11/24,THURSDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-11 19:59:00,2024-04-11 22:52:00,AA,2024-04-11 22:52:00,17.2,89,11.9,981.5,71,17.2,2024-04-11T23:00:00,0.0,2.718,301,150,16.10,10.80,2024-04-11 23:00:00
16,4/12/24,FRIDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-12 18:52:00,2024-04-12 21:47:00,UA,2024-04-12 21:47:00,9.5,78,3.1,975.0,64,9.5,2024-04-12T22:00:00,0.0,13.568,804,236,14.10,9.40,2024-04-12 22:00:00
17,4/12/24,FRIDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-12 19:59:00,2024-04-12 22:52:00,AA,2024-04-12 22:52:00,8.9,80,3.0,974.5,66,8.9,2024-04-12T23:00:00,0.0,0.130,804,240,13.95,9.36,2024-04-12 23:00:00
21,4/13/24,SATURDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-13 18:52:00,2024-04-13 21:47:00,UA,2024-04-13 21:47:00,3.0,74,1.3,992.7,70,6.4,2024-04-13T22:00:00,0.0,24.128,802,273,11.51,5.14,2024-04-13 22:00:00
22,4/13/24,SATURDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-13 19:59:00,2024-04-13 22:52:00,AA,2024-04-13 22:52:00,2.5,74,1.5,993.0,74,5.8,2024-04-13T23:00:00,0.0,24.128,802,268,9.31,4.63,2024-04-13 23:00:00

In [33]:
ord_w_merged_data = pd.merge_asof(ord_departures_df.sort_values('date_time'),
                                       ord_df.sort_values('date_time_map'),
                                       left_on='date_time', right_on='date_time_map', direction='nearest')

ord_w_merged_data.head()

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code,date_time,app_temp_x,clouds_x,dewpt_x,pres_x,rh_x,temp_x,timestamp_local_x,uv_x,vis_x,weather.code_x,wind_dir_x,wind_gust_spd_x,wind_spd_x,date_time_map_x,app_temp_y,clouds_y,dewpt_y,pres_y,rh_y,temp_y,timestamp_local_y,uv_y,vis_y,weather.code_y,wind_dir_y,wind_gust_spd_y,wind_spd_y,date_time_map_y
0,4/10/24,WEDNESDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-10 18:52:00,2024-04-10 21:47:00,UA,2024-04-10 21:47:00,12.6,76,6.6,999.0,67,12.6,2024-04-10T22:00:00,0.0,24.128,804,110,4.06,2.53,2024-04-10 22:00:00,12.3,92,3.3,981.0,54,12.3,2024-04-10T22:00:00,0.0,24.128,804,60,4.40,2.80,2024-04-10 22:00:00
1,4/10/24,WEDNESDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-10 19:59:00,2024-04-10 22:52:00,AA,2024-04-10 22:52:00,11.9,75,6.5,999.0,69,11.9,2024-04-10T23:00:00,0.0,24.128,804,120,4.00,2.40,2024-04-10 23:00:00,11.8,91,3.6,980.5,57,11.8,2024-04-10T23:00:00,0.0,24.128,804,56,4.66,2.93,2024-04-10 23:00:00
2,4/11/24,THURSDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-11 18:52:00,2024-04-11 21:47:00,UA,2024-04-11 21:47:00,17.1,89,11.5,982.0,70,17.1,2024-04-11T22:00:00,0.0,2.856,301,150,16.60,11.06,2024-04-11 22:00:00,9.2,82,5.2,972.5,76,9.2,2024-04-11T22:00:00,0.0,7.668,804,310,16.50,10.80,2024-04-11 22:00:00
3,4/11/24,THURSDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-11 19:59:00,2024-04-11 22:52:00,AA,2024-04-11 22:52:00,17.2,89,11.9,981.5,71,17.2,2024-04-11T23:00:00,0.0,2.718,301,150,16.10,10.80,2024-04-11 23:00:00,9.0,80,5.2,972.5,77,9.0,2024-04-11T23:00:00,0.0,8.376,804,306,15.86,10.40,2024-04-11 23:00:00
4,4/12/24,FRIDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-12 18:52:00,2024-04-12 21:47:00,UA,2024-04-12 21:47:00,9.5,78,3.1,975.0,64,9.5,2024-04-12T22:00:00,0.0,13.568,804,236,14.10,9.40,2024-04-12 22:00:00,10.3,12,0.9,990.0,52,10.3,2024-04-12T22:00:00,0.0,24.128,801,295,12.15,8.17,2024-04-12 22:00:00

In [37]:
final_merged_df = pd.concat([jfk_w_merged_data, mco_w_merged_data, ord_w_merged_data]).sort_values("date_time_map_y").reset_index(drop=True)
final_merged_df

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,scheduled_departure_time,scheduled_arrival_time,Carrier Code,date_time,app_temp_x,clouds_x,dewpt_x,pres_x,rh_x,temp_x,timestamp_local_x,uv_x,vis_x,weather.code_x,wind_dir_x,wind_gust_spd_x,wind_spd_x,date_time_map_x,app_temp_y,clouds_y,dewpt_y,pres_y,rh_y,temp_y,timestamp_local_y,uv_y,vis_y,weather.code_y,wind_dir_y,wind_gust_spd_y,wind_spd_y,date_time_map_y
0,4/10/24,WEDNESDAY,WN 5285,MCO,11:05 AM,1:45 PM,NaN,NaN,NaN,NaN,2024-04-10 11:05:00,2024-04-10 13:45:00,WN,2024-04-10 13:45:00,17.2,84,9.4,997.5,60,17.2,2024-04-10T14:00:00,2.9,19.696,804,280,6.90,4.40,2024-04-10 14:00:00,29.1,57,16.4,1013.5,47,28.8,2024-04-10T14:00:00,6.1,35.392,803,150,9.70,6.40,2024-04-10 14:00:00
1,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-10 13:33:00,2024-04-10 14:50:00,B6,2024-04-10 14:50:00,17.1,82,9.1,998.0,59,17.1,2024-04-10T15:00:00,2.5,18.720,804,283,6.50,4.26,2024-04-10 15:00:00,12.3,91,8.2,1015.0,76,12.3,2024-04-10T15:00:00,2.2,24.128,804,93,4.23,3.60,2024-04-10 15:00:00
2,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-10 14:55:00,2024-04-10 16:21:00,DL,2024-04-10 16:21:00,17.1,80,8.8,998.0,58,17.1,2024-04-10T16:00:00,1.8,24.128,804,286,6.10,4.13,2024-04-10 16:00:00,12.3,91,8.2,1015.0,76,12.3,2024-04-10T16:00:00,1.5,24.128,804,96,4.36,3.60,2024-04-10 16:00:00
3,4/10/24,WEDNESDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-10 13:35:00,2024-04-10 16:25:00,B6,2024-04-10 16:25:00,17.1,80,8.8,998.0,58,17.1,2024-04-10T16:00:00,1.8,24.128,804,286,6.10,4.13,2024-04-10 16:00:00,29.6,46,16.0,1009.5,44,29.5,2024-04-10T16:00:00,4.2,24.128,803,143,8.63,5.86,2024-04-10 16:00:00
4,4/10/24,WEDNESDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-10 18:52:00,2024-04-10 21:47:00,UA,2024-04-10 21:47:00,12.6,76,6.6,999.0,67,12.6,2024-04-10T22:00:00,0.0,24.128,804,110,4.06,2.53,2024-04-10 22:00:00,12.3,92,3.3,981.0,54,12.3,2024-04-10T22:00:00,0.0,24.128,804,60,4.40,2.80,2024-04-10 22:00:00
5,4/10/24,WEDNESDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-10 19:59:00,2024-04-10 22:52:00,AA,2024-04-10 22:52:00,11.9,75,6.5,999.0,69,11.9,2024-04-10T23:00:00,0.0,24.128,804,120,4.00,2.40,2024-04-10 23:00:00,11.8,91,3.6,980.5,57,11.8,2024-04-10T23:00:00,0.0,24.128,804,56,4.66,2.93,2024-04-10 23:00:00
6,4/11/24,THURSDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-11 11:35:00,2024-04-11 14:20:00,WN,2024-04-11 14:20:00,18.0,92,11.1,988.5,64,18.0,2024-04-11T14:00:00,2.6,24.128,804,140,16.40,10.80,2024-04-11 14:00:00,32.7,57,19.8,1007.0,52,30.8,2024-04-11T14:00:00,6.1,24.128,803,200,19.60,12.80,2024-04-11 14:00:00
7,4/11/24,THURSDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-11 13:33:00,2024-04-11 14:50:00,B6,2024-04-11 14:50:00,18.1,89,10.9,987.5,63,18.1,2024-04-11T15:00:00,2.2,21.472,804,143,17.20,11.33,2024-04-11 15:00:00,13.2,95,9.8,1009.0,80,13.2,2024-04-11T15:00:00,2.0,24.128,804,153,12.00,8.00,2024-04-11 15:00:00
8,4/11/24,THURSDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-11 13:35:00,2024-04-11 16:25:00,B6,2024-04-11 16:25:00,18.2,87,11.0,986.0,63,18.2,2024-04-11T16:00:00,1.7,17.024,804,146,18.00,11.86,2024-04-11 16:00:00,31.8,58,19.5,1005.5,53,30.2,2024-04-11T16:00:00,3.7,24.128,202,213,20.13,13.33,2024-04-11 16:00:00
9,4/11/24,THURSDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-11 14:55:00,2024-04-11 16:21:00,DL,2024-04-11 16:21:00,18.2,87,11.0,986.0,63,18.2,2024-04-11T16:00:00,1.7,17.024,804,146,18.00,11.86,2024-04-11 16:00:00,13.1,95,9.9,1008.0,81,13.1,2024-04-11T16:00:00,1.4,10.032,804,156,13.20,8.80,2024-04-11 16:00:00
10,4/11/24,THURSDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-11 18:52:00,2024-04-11 21:47:00,UA,2024-04-11 21:47:00,17.1,89,11.5,982.0,70,17.1,2024-04-11T22:00:00,0.0,2.856,301,150,16.60,11.06,2024-04-11 22:00:00,9.2,82,5.2,972.5,76,9.2,2024-04-11T22:00:00,0.0,7.668,804,310,16.50,10.80,2024-04-11 22:00:00
11,4/11/24,THURSDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-11 19:59:00,2024-04-11 22:52:00,AA,2024-04-11 22:52:00,17.2,89,11.9,981.5,71,17.2,2024-04-11T23:00:00,0.0,2.718,301,150,16.10,10.80,2024-04-11 23:00:00,9.0,80,5.2,972.5,77,9.0,2024-04-11T23:00:00,0.0,8.376,804,306,15.86,10.40,2024-04-11 23:00:00
12,4/12/24,FRIDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN,2024-04-12 11:35:00,2024-04-12 14:20:00,WN,2024-04-12 14:20:00,14.9,82,7.0,972.5,59,14.9,2024-04-12T14:00:00,3.0,17.456,804,230,14.10,9.67,2024-04-12 14:00:00,24.9,1,10.0,1016.5,38,25.3,2024-04-12T14:00:00,9.9,24.128,800,300,9.30,6.07,2024-04-12 14:00:00
13,4/12/24,FRIDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN,2024-04-12 13:33:00,2024-04-12 14:50:00,B6,2024-04-12 14:50:00,14.2,81,6.3,972.5,59,14.2,2024-04-12T15:00:00,2.6,24.128,804,230,14.15,9.63,2024-04-12 15:00:00,15.6,58,8.6,993.5,63,15.6,2024-04-12T15:00:00,3.5,24.128,803,223,14.95,10.17,2024-04-12 15:00:00
14,4/12/24,FRIDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-12 14:55:00,2024-04-12 16:21:00,DL,2024-04-12 16:21:00,13.5,79,5.9,972.0,60,13.5,2024-04-12T16:00:00,1.9,23.952,804,230,14.20,9.60,2024-04-12 16:00:00,15.1,53,7.9,993.5,62,15.1,2024-04-12T16:00:00,2.6,24.128,803,226,14.60,9.87,2024-04-12 16:00:00
15,4/12/24,FRIDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-12 13:35:00,2024-04-12 16:25:00,B6,2024-04-12 16:25:00,13.5,79,5.9,972.0,60,13.5,2024-04-12T16:00:00,1.9,23.952,804,230,14.20,9.60,2024-04-12 16:00:00,24.0,1,10.3,1015.5,41,24.4,2024-04-12T16:00:00,6.1,24.128,800,296,8.86,5.87,2024-04-12 16:00:00
16,4/12/24,FRIDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-12 18:52:00,2024-04-12 21:47:00,UA,2024-04-12 21:47:00,9.5,78,3.1,975.0,64,9.5,2024-04-12T22:00:00,0.0,13.568,804,236,14.10,9.40,2024-04-12 22:00:00,10.3,12,0.9,990.0,52,10.3,2024-04-12T22:00:00,0.0,24.128,801,295,12.15,8.17,2024-04-12 22:00:00
17,4/12/24,FRIDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-12 19:59:00,2024-04-12 22:52:00,AA,2024-04-12 22:52:00,8.9,80,3.0,974.5,66,8.9,2024-04-12T23:00:00,0.0,0.130,804,240,13.95,9.36,2024-04-12 23:00:00,9.7,10,0.8,990.5,54,9.7,2024-04-12T23:00:00,0.0,24.128,801,293,11.40,7.60,2024-04-12 23:00:00
18,4/13/24,SATURDAY,B6 116,JFK,1:12 PM,2:30 PM,NaN,NaN,NaN,NaN,2024-04-13 13:12:00,2024-04-13 14:30:00,B6,2024-04-13 14:30:00,8.5,76,1.6,988.0,62,8.5,2024-04-13T14:00:00,3.4,15.120,804,280,15.40,10.27,2024-04-13 14:00:00,12.9,61,2.2,1004.5,48,12.9,2024-04-13T14:00:00,4.2,24.128,803,280,14.20,9.47,2024-04-13 14:00:00
19,4/13/24,SATURDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN,2024-04-13 13:35:00,2024-04-13 16:25:00,B6,2024-04-13 16:25:00,8.1,73,1.1,989.0,61,8.1,2024-04-13T16:00:00,2.1,21.125,804,280,15.23,10.11,2024-04-13 16:00:00,24.3,3,8.7,1018.2,36,24.8,2024-04-13T16:00:00,6.1,24.128,801,23,7.23,5.04,2024-04-13 16:00:00
20,4/13/24,SATURDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN,2024-04-13 14:55:00,2024-04-13 16:21:00,DL,2024-04-13 16:21:00,8.1,73,1.1,989.0,61,8.1,2024-04-13T16:00:00,2.1,21.125,804,280,15.23,10.11,2024-04-13 16:00:00,12.4,54,2.0,1005.2,49,12.4,2024-04-13T16:00:00,2.5,24.128,803,280,13.63,9.04,2024-04-13 16:00:00
21,4/13/24,SATURDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN,2024-04-13 18:52:00,2024-04-13 21:47:00,UA,2024-04-13 21:47:00,3.0,74,1.3,992.7,70,6.4,2024-04-13T22:00:00,0.0,24.128,802,273,11.51,5.14,2024-04-13 22:00:00,13.7,53,2.9,979.0,48,13.7,2024-04-13T22:00:00,0.0,23.712,801,167,12.11,4.12,2024-04-13 22:00:00
22,4/13/24,SATURDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN,2024-04-13 19:59:00,2024-04-13 22:52:00,AA,2024-04-13 22:52:00,2.5,74,1.5,993.0,74,5.8,2024-04-13T23:00:00,0.0,24.128,802,268,9.31,4.63,2024-04-13 23:00:00,13.3,53,3.4,979.0,51,13.3,2024-04-13T23:00:00,0.0,23.792,801,186,9.07,4.12,2024-04-13 23:00:00

In [57]:
rename_cols = {
    "ORIGIN" : "Origin Airport"
    
}
final_merged_df.rename(columns=rename_cols, inplace=True)

In [58]:
final_merged_df["Scheduled Elapsed Time (Minutes)"] = (final_merged_df["scheduled_arrival_time"] - final_merged_df["scheduled_departure_time"]).dt.total_seconds() // 60

final_merged_df

,Origin Airport,scheduled_departure_time,scheduled_arrival_time,Carrier Code,app_temp_x,clouds_x,dewpt_x,pres_x,rh_x,temp_x,uv_x,vis_x,weather.code_x,wind_dir_x,wind_gust_spd_x,wind_spd_x,app_temp_y,clouds_y,dewpt_y,pres_y,rh_y,temp_y,uv_y,vis_y,weather.code_y,wind_dir_y,wind_gust_spd_y,wind_spd_y,Scheduled Elapsed Time (Minutes)
0,MCO,2024-04-10 11:05:00,2024-04-10 13:45:00,WN,17.2,84,9.4,997.5,60,17.2,2.9,19.696,804,280,6.90,4.40,29.1,57,16.4,1013.5,47,28.8,6.1,35.392,803,150,9.70,6.40,160.0
1,JFK,2024-04-10 13:33:00,2024-04-10 14:50:00,B6,17.1,82,9.1,998.0,59,17.1,2.5,18.720,804,283,6.50,4.26,12.3,91,8.2,1015.0,76,12.3,2.2,24.128,804,93,4.23,3.60,77.0
2,JFK,2024-04-10 14:55:00,2024-04-10 16:21:00,DL,17.1,80,8.8,998.0,58,17.1,1.8,24.128,804,286,6.10,4.13,12.3,91,8.2,1015.0,76,12.3,1.5,24.128,804,96,4.36,3.60,86.0
3,MCO,2024-04-10 13:35:00,2024-04-10 16:25:00,B6,17.1,80,8.8,998.0,58,17.1,1.8,24.128,804,286,6.10,4.13,29.6,46,16.0,1009.5,44,29.5,4.2,24.128,803,143,8.63,5.86,170.0
4,ORD,2024-04-10 18:52:00,2024-04-10 21:47:00,UA,12.6,76,6.6,999.0,67,12.6,0.0,24.128,804,110,4.06,2.53,12.3,92,3.3,981.0,54,12.3,0.0,24.128,804,60,4.40,2.80,175.0
5,ORD,2024-04-10 19:59:00,2024-04-10 22:52:00,AA,11.9,75,6.5,999.0,69,11.9,0.0,24.128,804,120,4.00,2.40,11.8,91,3.6,980.5,57,11.8,0.0,24.128,804,56,4.66,2.93,173.0
6,MCO,2024-04-11 11:35:00,2024-04-11 14:20:00,WN,18.0,92,11.1,988.5,64,18.0,2.6,24.128,804,140,16.40,10.80,32.7,57,19.8,1007.0,52,30.8,6.1,24.128,803,200,19.60,12.80,165.0
7,JFK,2024-04-11 13:33:00,2024-04-11 14:50:00,B6,18.1,89,10.9,987.5,63,18.1,2.2,21.472,804,143,17.20,11.33,13.2,95,9.8,1009.0,80,13.2,2.0,24.128,804,153,12.00,8.00,77.0
8,MCO,2024-04-11 13:35:00,2024-04-11 16:25:00,B6,18.2,87,11.0,986.0,63,18.2,1.7,17.024,804,146,18.00,11.86,31.8,58,19.5,1005.5,53,30.2,3.7,24.128,202,213,20.13,13.33,170.0
9,JFK,2024-04-11 14:55:00,2024-04-11 16:21:00,DL,18.2,87,11.0,986.0,63,18.2,1.7,17.024,804,146,18.00,11.86,13.1,95,9.9,1008.0,81,13.1,1.4,10.032,804,156,13.20,8.80,86.0
10,ORD,2024-04-11 18:52:00,2024-04-11 21:47:00,UA,17.1,89,11.5,982.0,70,17.1,0.0,2.856,301,150,16.60,11.06,9.2,82,5.2,972.5,76,9.2,0.0,7.668,804,310,16.50,10.80,175.0
11,ORD,2024-04-11 19:59:00,2024-04-11 22:52:00,AA,17.2,89,11.9,981.5,71,17.2,0.0,2.718,301,150,16.10,10.80,9.0,80,5.2,972.5,77,9.0,0.0,8.376,804,306,15.86,10.40,173.0
12,MCO,2024-04-12 11:35:00,2024-04-12 14:20:00,WN,14.9,82,7.0,972.5,59,14.9,3.0,17.456,804,230,14.10,9.67,24.9,1,10.0,1016.5,38,25.3,9.9,24.128,800,300,9.30,6.07,165.0
13,JFK,2024-04-12 13:33:00,2024-04-12 14:50:00,B6,14.2,81,6.3,972.5,59,14.2,2.6,24.128,804,230,14.15,9.63,15.6,58,8.6,993.5,63,15.6,3.5,24.128,803,223,14.95,10.17,77.0
14,JFK,2024-04-12 14:55:00,2024-04-12 16:21:00,DL,13.5,79,5.9,972.0,60,13.5,1.9,23.952,804,230,14.20,9.60,15.1,53,7.9,993.5,62,15.1,2.6,24.128,803,226,14.60,9.87,86.0
15,MCO,2024-04-12 13:35:00,2024-04-12 16:25:00,B6,13.5,79,5.9,972.0,60,13.5,1.9,23.952,804,230,14.20,9.60,24.0,1,10.3,1015.5,41,24.4,6.1,24.128,800,296,8.86,5.87,170.0
16,ORD,2024-04-12 18:52:00,2024-04-12 21:47:00,UA,9.5,78,3.1,975.0,64,9.5,0.0,13.568,804,236,14.10,9.40,10.3,12,0.9,990.0,52,10.3,0.0,24.128,801,295,12.15,8.17,175.0
17,ORD,2024-04-12 19:59:00,2024-04-12 22:52:00,AA,8.9,80,3.0,974.5,66,8.9,0.0,0.130,804,240,13.95,9.36,9.7,10,0.8,990.5,54,9.7,0.0,24.128,801,293,11.40,7.60,173.0
18,JFK,2024-04-13 13:12:00,2024-04-13 14:30:00,B6,8.5,76,1.6,988.0,62,8.5,3.4,15.120,804,280,15.40,10.27,12.9,61,2.2,1004.5,48,12.9,4.2,24.128,803,280,14.20,9.47,78.0
19,MCO,2024-04-13 13:35:00,2024-04-13 16:25:00,B6,8.1,73,1.1,989.0,61,8.1,2.1,21.125,804,280,15.23,10.11,24.3,3,8.7,1018.2,36,24.8,6.1,24.128,801,23,7.23,5.04,170.0
20,JFK,2024-04-13 14:55:00,2024-04-13 16:21:00,DL,8.1,73,1.1,989.0,61,8.1,2.1,21.125,804,280,15.23,10.11,12.4,54,2.0,1005.2,49,12.4,2.5,24.128,803,280,13.63,9.04,86.0
21,ORD,2024-04-13 18:52:00,2024-04-13 21:47:00,UA,3.0,74,1.3,992.7,70,6.4,0.0,24.128,802,273,11.51,5.14,13.7,53,2.9,979.0,48,13.7,0.0,23.712,801,167,12.11,4.12,175.0
22,ORD,2024-04-13 19:59:00,2024-04-13 22:52:00,AA,2.5,74,1.5,993.0,74,5.8,0.0,24.128,802,268,9.31,4.63,13.3,53,3.4,979.0,51,13.3,0.0,23.792,801,186,9.07,4.12,173.0

In [59]:
final_merged_df.shape

(23, 29)

In [44]:
final_merged_df.columns

Index(['DATE', 'DAY', 'FLIGHT NUMBER', 'ORIGIN', 'DEPARTURE TIME',
       'ARRIVAL TIME', 'ARRIVAL STATUS', 'ARRIVAL STATUS_Prev_flight_early',
       'ARRIVAL STATUS_Prev_flight_ontime', 'ARRIVAL STATUS_Prev_flight_late',
       'scheduled_departure_time', 'scheduled_arrival_time', 'Carrier Code',
       'date_time', 'app_temp_x', 'clouds_x', 'dewpt_x', 'pres_x', 'rh_x',
       'temp_x', 'timestamp_local_x', 'uv_x', 'vis_x', 'weather.code_x',
       'wind_dir_x', 'wind_gust_spd_x', 'wind_spd_x', 'date_time_map_x',
       'app_temp_y', 'clouds_y', 'dewpt_y', 'pres_y', 'rh_y', 'temp_y',
       'timestamp_local_y', 'uv_y', 'vis_y', 'weather.code_y', 'wind_dir_y',
       'wind_gust_spd_y', 'wind_spd_y', 'date_time_map_y',
       'Scheduled Elapsed Time (Minutes)'],
      dtype='object')

In [60]:
drop_cols = ["DATE", "DAY", "FLIGHT NUMBER", 'DEPARTURE TIME',
       'ARRIVAL TIME', 'ARRIVAL STATUS', 'ARRIVAL STATUS_Prev_flight_early',
       'ARRIVAL STATUS_Prev_flight_ontime', 'ARRIVAL STATUS_Prev_flight_late',  'date_time', 'timestamp_local_x', 'timestamp_local_y', 'date_time_map_x',
            'date_time_map_y']

In [52]:
final_merged_df.drop(columns=drop_cols, inplace=True)

In [61]:
final_merged_df.to_csv("./data/modified/initial_predictions.csv", index=False)