In [1]:
import pandas as pd

In [2]:
arrivals_df = pd.read_csv("./data/modified/arrivals_jfk_mco_ord.csv")
arrivals_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport
0,UA,01/01/2023,2645,N23721,ORD,23:57,23:47,107,100,-10,23:41,6,0,0,0,0,0,SYR
1,UA,01/02/2023,1998,N802UA,ORD,21:07,20:46,113,89,-21,20:43,3,0,0,0,0,0,SYR
2,UA,01/03/2023,1998,N854UA,ORD,21:07,21:04,113,111,-3,20:58,6,0,0,0,0,0,SYR
3,UA,01/04/2023,1998,N893UA,ORD,21:17,21:31,113,110,14,21:26,5,0,0,0,0,0,SYR
4,UA,01/05/2020,2012,N825UA,ORD,21:47,21:55,107,94,8,21:50,5,0,0,0,0,0,SYR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23629,EV,11/20/2019,4103,N609UX,ORD,09:19,09:17,109,108,-2,09:10,7,0,0,0,0,0,SYR
23630,EV,11/24/2019,4461,N609UX,ORD,12:03,11:58,108,107,-5,11:54,4,0,0,0,0,0,SYR
23631,EV,12/11/2019,4063,N607UX,ORD,12:23,12:39,108,105,16,12:34,5,10,0,0,0,6,SYR
23632,EV,12/14/2019,4486,N612UX,ORD,09:04,08:53,109,109,-11,08:44,9,0,0,0,0,0,SYR
23633,EV,12/15/2019,4486,N616UX,ORD,12:23,12:51,108,116,28,12:46,5,15,0,8,0,5,SYR

In [3]:
arrivals_df.dtypes

Carrier Code                                object
Date (MM/DD/YYYY)                           object
Flight Number                                int64
Tail Number                                 object
Origin Airport                              object
Scheduled Arrival Time                      object
Actual Arrival Time                         object
Scheduled Elapsed Time (Minutes)             int64
Actual Elapsed Time (Minutes)                int64
Arrival Delay (Minutes)                      int64
Wheels-on Time                              object
Taxi-In time (Minutes)                       int64
Delay Carrier (Minutes)                      int64
Delay Weather (Minutes)                      int64
Delay National Aviation System (Minutes)     int64
Delay Security (Minutes)                     int64
Delay Late Aircraft Arrival (Minutes)        int64
Destination Airport                         object
dtype: object

In [4]:
departures_df = pd.read_csv("./data/modified/departures.csv", index_col=0)
departures_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Origin Airport
0,G4,01/02/2020,1737,241NV,SYR,06:30,06:29,176,167,-1,06:42,13,0,0,0,0,0,FLL
1,G4,01/03/2019,1720,226NV,SYR,06:50,06:49,182,167,-1,07:01,12,0,0,0,0,0,FLL
2,G4,01/03/2021,1744,245NV,SYR,16:25,17:40,178,168,75,17:53,13,0,0,0,0,65,FLL
3,G4,01/03/2022,962,222NV,SYR,06:15,06:15,176,175,0,06:30,15,0,0,0,0,0,FLL
4,G4,01/03/2023,523,234NV,SYR,06:30,10:34,182,170,244,10:51,17,232,0,0,0,0,FLL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56537,YX,12/16/2023,4312,N128HQ,SYR,19:45,19:39,213,198,-6,20:05,26,0,0,0,0,0,MIA
56538,YX,12/18/2021,5008,N127HQ,SYR,19:55,19:52,186,182,-3,20:10,18,0,0,0,0,0,MIA
56539,YX,12/23/2023,4371,N102HQ,SYR,19:44,19:42,206,187,-2,19:58,16,0,0,0,0,0,MIA
56540,YX,12/25/2021,5008,N425YX,SYR,19:55,19:49,186,194,-6,20:10,21,0,0,0,0,0,MIA
56541,YX,12/30/2023,4371,N444YX,SYR,19:44,19:38,206,185,-6,19:58,20,0,0,0,0,0,MIA

In [5]:
weather_df = pd.read_csv("./data/modified/weather_mco_ord_jfk_syr_tz.csv")
weather_df

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds,date_time
0,MCO,1546321980,N,69.0,29.0,2900.0,Partly Cloudy,67.0,69.0,93.0,...,69.0,190.0,S,8.0,0.0,Low,69.0,0.0,SCT,2019-01-01 00:53:00-05:00
1,MCO,1546325580,N,67.0,33.0,3300.0,Fair,65.0,67.0,93.0,...,67.0,200.0,SSW,6.0,0.0,Low,67.0,0.0,FEW,2019-01-01 01:53:00-05:00
2,MCO,1546329180,N,66.0,33.0,3300.0,Fair,64.0,66.0,93.0,...,66.0,210.0,SSW,3.0,0.0,Low,66.0,0.0,FEW,2019-01-01 02:53:00-05:00
3,MCO,1546331160,N,65.0,20.0,2000.0,Fog,64.0,65.0,97.0,...,65.0,190.0,S,3.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:26:00-05:00
4,MCO,1546331700,N,65.0,33.0,3300.0,Fair,65.0,65.0,100.0,...,65.0,NaN,CALM,0.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:35:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219795,SYR,1712523240,D,58.0,34.0,3400.0,Fair,26.0,58.0,30.0,...,58.0,340.0,NNW,12.0,0.0,Low,58.0,2.0,CLR,2024-04-07 16:54:00-04:00
219796,SYR,1712526840,D,57.0,34.0,3400.0,Fair,26.0,57.0,30.0,...,57.0,310.0,NW,15.0,0.0,Low,57.0,1.0,CLR,2024-04-07 17:54:00-04:00
219797,SYR,1712530440,D,56.0,34.0,3400.0,Fair,25.0,56.0,30.0,...,56.0,310.0,NW,12.0,0.0,Low,56.0,0.0,CLR,2024-04-07 18:54:00-04:00
219798,SYR,1712534040,N,50.0,33.0,3300.0,Fair,26.0,50.0,39.0,...,50.0,310.0,NW,7.0,0.0,Low,50.0,0.0,FEW,2024-04-07 19:54:00-04:00
219799,SYR,1712537640,N,47.0,33.0,3300.0,Fair,27.0,47.0,46.0,...,44.0,340.0,NNW,6.0,0.0,Low,44.0,0.0,FEW,2024-04-07 20:54:00-04:00

In [6]:
weather_df.dtypes

key                object
valid_time_gmt      int64
day_ind            object
temp              float64
wx_icon           float64
icon_extd         float64
wx_phrase          object
dewPt             float64
heat_index        float64
rh                float64
pressure          float64
vis               float64
wc                float64
wdir              float64
wdir_cardinal      object
wspd              float64
precip_hrly       float64
uv_desc            object
feels_like        float64
uv_index          float64
clds               object
date_time          object
dtype: object

In [7]:
weather_df["date_time"] = pd.to_datetime(weather_df["date_time"])
weather_df

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds,date_time
0,MCO,1546321980,N,69.0,29.0,2900.0,Partly Cloudy,67.0,69.0,93.0,...,69.0,190.0,S,8.0,0.0,Low,69.0,0.0,SCT,2019-01-01 00:53:00-05:00
1,MCO,1546325580,N,67.0,33.0,3300.0,Fair,65.0,67.0,93.0,...,67.0,200.0,SSW,6.0,0.0,Low,67.0,0.0,FEW,2019-01-01 01:53:00-05:00
2,MCO,1546329180,N,66.0,33.0,3300.0,Fair,64.0,66.0,93.0,...,66.0,210.0,SSW,3.0,0.0,Low,66.0,0.0,FEW,2019-01-01 02:53:00-05:00
3,MCO,1546331160,N,65.0,20.0,2000.0,Fog,64.0,65.0,97.0,...,65.0,190.0,S,3.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:26:00-05:00
4,MCO,1546331700,N,65.0,33.0,3300.0,Fair,65.0,65.0,100.0,...,65.0,NaN,CALM,0.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:35:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219795,SYR,1712523240,D,58.0,34.0,3400.0,Fair,26.0,58.0,30.0,...,58.0,340.0,NNW,12.0,0.0,Low,58.0,2.0,CLR,2024-04-07 16:54:00-04:00
219796,SYR,1712526840,D,57.0,34.0,3400.0,Fair,26.0,57.0,30.0,...,57.0,310.0,NW,15.0,0.0,Low,57.0,1.0,CLR,2024-04-07 17:54:00-04:00
219797,SYR,1712530440,D,56.0,34.0,3400.0,Fair,25.0,56.0,30.0,...,56.0,310.0,NW,12.0,0.0,Low,56.0,0.0,CLR,2024-04-07 18:54:00-04:00
219798,SYR,1712534040,N,50.0,33.0,3300.0,Fair,26.0,50.0,39.0,...,50.0,310.0,NW,7.0,0.0,Low,50.0,0.0,FEW,2024-04-07 19:54:00-04:00
219799,SYR,1712537640,N,47.0,33.0,3300.0,Fair,27.0,47.0,46.0,...,44.0,340.0,NNW,6.0,0.0,Low,44.0,0.0,FEW,2024-04-07 20:54:00-04:00

In [8]:
weather_df.isna().sum()

key                   0
valid_time_gmt        0
day_ind               0
temp                 10
wx_icon              14
icon_extd            14
wx_phrase            14
dewPt                19
heat_index           19
rh                   19
pressure             54
vis                  17
wc                  191
wdir              20154
wdir_cardinal       187
wspd                187
precip_hrly           0
uv_desc              56
feels_like           64
uv_index             56
clds                 20
date_time             0
dtype: int64

In [9]:
len(weather_df.columns)

22

In [10]:
corr = weather_df.corr(numeric_only=True)

In [11]:
corr_pairs = corr.unstack().sort_values(ascending=False).drop_duplicates().head(15)
corr_pairs

valid_time_gmt  valid_time_gmt    1.000000
wc              feels_like        0.997847
temp            heat_index        0.997177
feels_like      temp              0.993734
                heat_index        0.993623
wc              temp              0.993555
                heat_index        0.988525
icon_extd       wx_icon           0.951590
dewPt           feels_like        0.921275
wc              dewPt             0.920601
dewPt           temp              0.918927
                heat_index        0.917293
icon_extd       vis               0.626319
vis             wx_icon           0.570689
uv_index        heat_index        0.427652
dtype: float64

In [12]:
weather_corr_columns = set()
for pair in corr_pairs.index:
    weather_corr_columns.add(pair[0])
    weather_corr_columns.add(pair[1])
weather_corr_columns

{'dewPt',
 'feels_like',
 'heat_index',
 'icon_extd',
 'temp',
 'uv_index',
 'valid_time_gmt',
 'vis',
 'wc',
 'wx_icon'}

In [13]:
weather_cat_cols = weather_df.select_dtypes(include=['object'])
weather_cat_cols

,key,day_ind,wx_phrase,wdir_cardinal,uv_desc,clds,date_time
0,MCO,N,Partly Cloudy,S,Low,SCT,2019-01-01 00:53:00-05:00
1,MCO,N,Fair,SSW,Low,FEW,2019-01-01 01:53:00-05:00
2,MCO,N,Fair,SSW,Low,FEW,2019-01-01 02:53:00-05:00
3,MCO,N,Fog,S,Low,FEW,2019-01-01 03:26:00-05:00
4,MCO,N,Fair,CALM,Low,FEW,2019-01-01 03:35:00-05:00
...,...,...,...,...,...,...,...
219795,SYR,D,Fair,NNW,Low,CLR,2024-04-07 16:54:00-04:00
219796,SYR,D,Fair,NW,Low,CLR,2024-04-07 17:54:00-04:00
219797,SYR,D,Fair,NW,Low,CLR,2024-04-07 18:54:00-04:00
219798,SYR,N,Fair,NW,Low,FEW,2024-04-07 19:54:00-04:00
219799,SYR,N,Fair,NNW,Low,FEW,2024-04-07 20:54:00-04:00

In [11]:
weather_df.select_dtypes(include=['object'])

,key,day_ind,wx_phrase,wdir_cardinal,uv_desc,clds,date_time
0,MCO,N,Partly Cloudy,S,Low,SCT,2019-01-01 00:53:00-05:00
1,MCO,N,Fair,SSW,Low,FEW,2019-01-01 01:53:00-05:00
2,MCO,N,Fair,SSW,Low,FEW,2019-01-01 02:53:00-05:00
3,MCO,N,Fog,S,Low,FEW,2019-01-01 03:26:00-05:00
4,MCO,N,Fair,CALM,Low,FEW,2019-01-01 03:35:00-05:00
...,...,...,...,...,...,...,...
219795,SYR,D,Fair,NNW,Low,CLR,2024-04-07 16:54:00-04:00
219796,SYR,D,Fair,NW,Low,CLR,2024-04-07 17:54:00-04:00
219797,SYR,D,Fair,NW,Low,CLR,2024-04-07 18:54:00-04:00
219798,SYR,N,Fair,NW,Low,FEW,2024-04-07 19:54:00-04:00
219799,SYR,N,Fair,NNW,Low,FEW,2024-04-07 20:54:00-04:00