In [54]:
import pandas as pd

In [55]:
arrivals_df = pd.read_csv("./data/modified/arrivals_jfk_mco_ord.csv")
arrivals_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport
0,UA,01/01/2023,2645,N23721,ORD,23:57,23:47,107,100,-10,23:41,6,0,0,0,0,0,SYR
1,UA,01/02/2023,1998,N802UA,ORD,21:07,20:46,113,89,-21,20:43,3,0,0,0,0,0,SYR
2,UA,01/03/2023,1998,N854UA,ORD,21:07,21:04,113,111,-3,20:58,6,0,0,0,0,0,SYR
3,UA,01/04/2023,1998,N893UA,ORD,21:17,21:31,113,110,14,21:26,5,0,0,0,0,0,SYR
4,UA,01/05/2020,2012,N825UA,ORD,21:47,21:55,107,94,8,21:50,5,0,0,0,0,0,SYR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17459,WN,12/28/2023,3149,N462WN,MCO,13:00,13:08,160,147,8,13:05,3,0,0,0,0,0,SYR
17460,WN,12/29/2023,3149,N551WN,MCO,13:00,12:46,160,150,-14,12:43,3,0,0,0,0,0,SYR
17461,WN,12/30/2023,3208,N283WN,MCO,12:30,12:23,160,157,-7,12:14,9,0,0,0,0,0,SYR
17462,WN,12/31/2022,1149,N7734H,MCO,14:05,14:12,160,147,7,14:10,2,0,0,0,0,0,SYR
17463,WN,12/31/2023,3149,N8684F,MCO,14:10,13:58,160,152,-12,13:55,3,0,0,0,0,0,SYR

In [56]:
arrivals_df["date"] = pd.to_datetime(arrivals_df["Date (MM/DD/YYYY)"], format="%m/%d/%Y")
arrivals_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport,date
0,UA,01/01/2023,2645,N23721,ORD,23:57,23:47,107,100,-10,23:41,6,0,0,0,0,0,SYR,2023-01-01
1,UA,01/02/2023,1998,N802UA,ORD,21:07,20:46,113,89,-21,20:43,3,0,0,0,0,0,SYR,2023-01-02
2,UA,01/03/2023,1998,N854UA,ORD,21:07,21:04,113,111,-3,20:58,6,0,0,0,0,0,SYR,2023-01-03
3,UA,01/04/2023,1998,N893UA,ORD,21:17,21:31,113,110,14,21:26,5,0,0,0,0,0,SYR,2023-01-04
4,UA,01/05/2020,2012,N825UA,ORD,21:47,21:55,107,94,8,21:50,5,0,0,0,0,0,SYR,2020-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17459,WN,12/28/2023,3149,N462WN,MCO,13:00,13:08,160,147,8,13:05,3,0,0,0,0,0,SYR,2023-12-28
17460,WN,12/29/2023,3149,N551WN,MCO,13:00,12:46,160,150,-14,12:43,3,0,0,0,0,0,SYR,2023-12-29
17461,WN,12/30/2023,3208,N283WN,MCO,12:30,12:23,160,157,-7,12:14,9,0,0,0,0,0,SYR,2023-12-30
17462,WN,12/31/2022,1149,N7734H,MCO,14:05,14:12,160,147,7,14:10,2,0,0,0,0,0,SYR,2022-12-31
17463,WN,12/31/2023,3149,N8684F,MCO,14:10,13:58,160,152,-12,13:55,3,0,0,0,0,0,SYR,2023-12-31

In [70]:
arrivals_df.corr(numeric_only=True)

,Flight Number,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
Flight Number,1.000000,-0.316247,-0.252278,-0.120908,0.070060,-0.070970,-0.000677,-0.015391,-0.026538,-0.083564
Scheduled Elapsed Time (Minutes),-0.316247,1.000000,0.761821,0.098743,0.088035,0.047621,0.009854,0.027277,0.031859,0.065681
Actual Elapsed Time (Minutes),-0.252278,0.761821,1.000000,0.197450,0.286885,0.071884,0.029861,0.189107,0.031205,0.088955
Arrival Delay (Minutes),-0.120908,0.098743,0.197450,1.000000,0.085916,0.668911,0.313417,0.367314,0.023787,0.657613
Taxi-In time (Minutes),0.070060,0.088035,0.286885,0.085916,1.000000,0.015856,0.018792,0.113080,-0.008510,0.046539
Delay Carrier (Minutes),-0.070970,0.047621,0.071884,0.668911,0.015856,1.000000,-0.002220,0.033304,-0.004986,0.129586
Delay Weather (Minutes),-0.000677,0.009854,0.029861,0.313417,0.018792,-0.002220,1.000000,0.032767,-0.001357,0.040635
Delay National Aviation System (Minutes),-0.015391,0.027277,0.189107,0.367314,0.113080,0.033304,0.032767,1.000000,0.006024,0.067898
Delay Security (Minutes),-0.026538,0.031859,0.031205,0.023787,-0.008510,-0.004986,-0.001357,0.006024,1.000000,0.028277
Delay Late Aircraft Arrival (Minutes),-0.083564,0.065681,0.088955,0.657613,0.046539,0.129586,0.040635,0.067898,0.028277,1.000000

In [57]:
a_corr = arrivals_df.corr(numeric_only=True).abs().unstack().sort_values(ascending=False).drop_duplicates()
a_corr

Flight Number                             Flight Number                               1.000000
Scheduled Elapsed Time (Minutes)          Actual Elapsed Time (Minutes)               0.761821
Delay Carrier (Minutes)                   Arrival Delay (Minutes)                     0.668911
Delay Late Aircraft Arrival (Minutes)     Arrival Delay (Minutes)                     0.657613
Delay National Aviation System (Minutes)  Arrival Delay (Minutes)                     0.367314
Scheduled Elapsed Time (Minutes)          Flight Number                               0.316247
Arrival Delay (Minutes)                   Delay Weather (Minutes)                     0.313417
Actual Elapsed Time (Minutes)             Taxi-In time (Minutes)                      0.286885
                                          Flight Number                               0.252278
Arrival Delay (Minutes)                   Actual Elapsed Time (Minutes)               0.197450
Delay National Aviation System (Minutes)  Actual Elapsed Time (Minutes)               0.189107
Delay Carrier (Minutes)                   Delay Late Aircraft Arrival (Minutes)       0.129586
Arrival Delay (Minutes)                   Flight Number                               0.120908
Taxi-In time (Minutes)                    Delay National Aviation System (Minutes)    0.113080
Arrival Delay (Minutes)                   Scheduled Elapsed Time (Minutes)            0.098743
Delay Late Aircraft Arrival (Minutes)     Actual Elapsed Time (Minutes)               0.088955
Taxi-In time (Minutes)                    Scheduled Elapsed Time (Minutes)            0.088035
Arrival Delay (Minutes)                   Taxi-In time (Minutes)                      0.085916
Delay Late Aircraft Arrival (Minutes)     Flight Number                               0.083564
Actual Elapsed Time (Minutes)             Delay Carrier (Minutes)                     0.071884
Flight Number                             Delay Carrier (Minutes)                     0.070970
Taxi-In time (Minutes)                    Flight Number                               0.070060
Delay Late Aircraft Arrival (Minutes)     Delay National Aviation System (Minutes)    0.067898
                                          Scheduled Elapsed Time (Minutes)            0.065681
Delay Carrier (Minutes)                   Scheduled Elapsed Time (Minutes)            0.047621
Delay Late Aircraft Arrival (Minutes)     Taxi-In time (Minutes)                      0.046539
                                          Delay Weather (Minutes)                     0.040635
Delay National Aviation System (Minutes)  Delay Carrier (Minutes)                     0.033304
                                          Delay Weather (Minutes)                     0.032767
Scheduled Elapsed Time (Minutes)          Delay Security (Minutes)                    0.031859
Delay Security (Minutes)                  Actual Elapsed Time (Minutes)               0.031205
Actual Elapsed Time (Minutes)             Delay Weather (Minutes)                     0.029861
Delay Late Aircraft Arrival (Minutes)     Delay Security (Minutes)                    0.028277
Delay National Aviation System (Minutes)  Scheduled Elapsed Time (Minutes)            0.027277
Flight Number                             Delay Security (Minutes)                    0.026538
Delay Security (Minutes)                  Arrival Delay (Minutes)                     0.023787
Taxi-In time (Minutes)                    Delay Weather (Minutes)                     0.018792
                                          Delay Carrier (Minutes)                     0.015856
Flight Number                             Delay National Aviation System (Minutes)    0.015391
Delay Weather (Minutes)                   Scheduled Elapsed Time (Minutes)            0.009854
Delay Security (Minutes)                  Taxi-In time (Minutes)                      0.008510
Delay National Aviation System (Minutes)  Delay Security (Minutes)                    0.006024
Delay Carrier (Minutes)                   Delay Security (Minutes)                    0.004986
Delay Weather (Minutes)                   Delay Carrier (Minutes)                     0.002220
                                          Delay Security (Minutes)                    0.001357
Flight Number                             Delay Weather (Minutes)                     0.000677
dtype: float64

In [58]:
a_corr_pairs = a_corr[a_corr>0.1]

In [59]:
a_corr_columns = set()
for pair in a_corr_pairs.index:
    a_corr_columns.add(pair[0])
    a_corr_columns.add(pair[1])
a_corr_columns

{'Actual Elapsed Time (Minutes)',
 'Arrival Delay (Minutes)',
 'Delay Carrier (Minutes)',
 'Delay Late Aircraft Arrival (Minutes)',
 'Delay National Aviation System (Minutes)',
 'Delay Weather (Minutes)',
 'Flight Number',
 'Scheduled Elapsed Time (Minutes)',
 'Taxi-In time (Minutes)'}

In [60]:
a_cat_cols = arrivals_df.select_dtypes(include=['object'])
a_cat_cols

,Carrier Code,Date (MM/DD/YYYY),Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Wheels-on Time,Destination Airport
0,UA,01/01/2023,N23721,ORD,23:57,23:47,23:41,SYR
1,UA,01/02/2023,N802UA,ORD,21:07,20:46,20:43,SYR
2,UA,01/03/2023,N854UA,ORD,21:07,21:04,20:58,SYR
3,UA,01/04/2023,N893UA,ORD,21:17,21:31,21:26,SYR
4,UA,01/05/2020,N825UA,ORD,21:47,21:55,21:50,SYR
...,...,...,...,...,...,...,...,...
17459,WN,12/28/2023,N462WN,MCO,13:00,13:08,13:05,SYR
17460,WN,12/29/2023,N551WN,MCO,13:00,12:46,12:43,SYR
17461,WN,12/30/2023,N283WN,MCO,12:30,12:23,12:14,SYR
17462,WN,12/31/2022,N7734H,MCO,14:05,14:12,14:10,SYR
17463,WN,12/31/2023,N8684F,MCO,14:10,13:58,13:55,SYR

In [ ]:
drop_flight_cols = ["Tail Number", "Actual Arrival Time", "Wheels-on Time"]

In [17]:
arrivals_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport,date
0,UA,01/01/2023,2645,N23721,ORD,23:57,23:47,107,100,-10,23:41,6,0,0,0,0,0,SYR,2023-01-01
1,UA,01/02/2023,1998,N802UA,ORD,21:07,20:46,113,89,-21,20:43,3,0,0,0,0,0,SYR,2023-01-02
2,UA,01/03/2023,1998,N854UA,ORD,21:07,21:04,113,111,-3,20:58,6,0,0,0,0,0,SYR,2023-01-03
3,UA,01/04/2023,1998,N893UA,ORD,21:17,21:31,113,110,14,21:26,5,0,0,0,0,0,SYR,2023-01-04
4,UA,01/05/2020,2012,N825UA,ORD,21:47,21:55,107,94,8,21:50,5,0,0,0,0,0,SYR,2020-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23629,EV,11/20/2019,4103,N609UX,ORD,09:19,09:17,109,108,-2,09:10,7,0,0,0,0,0,SYR,2019-11-20
23630,EV,11/24/2019,4461,N609UX,ORD,12:03,11:58,108,107,-5,11:54,4,0,0,0,0,0,SYR,2019-11-24
23631,EV,12/11/2019,4063,N607UX,ORD,12:23,12:39,108,105,16,12:34,5,10,0,0,0,6,SYR,2019-12-11
23632,EV,12/14/2019,4486,N612UX,ORD,09:04,08:53,109,109,-11,08:44,9,0,0,0,0,0,SYR,2019-12-14
23633,EV,12/15/2019,4486,N616UX,ORD,12:23,12:51,108,116,28,12:46,5,15,0,8,0,5,SYR,2019-12-15

In [53]:
arrivals_df.drop_duplicates()

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport,date
0,UA,01/01/2023,2645,N23721,ORD,23:57,23:47,107,100,-10,23:41,6,0,0,0,0,0,SYR,2023-01-01
1,UA,01/02/2023,1998,N802UA,ORD,21:07,20:46,113,89,-21,20:43,3,0,0,0,0,0,SYR,2023-01-02
2,UA,01/03/2023,1998,N854UA,ORD,21:07,21:04,113,111,-3,20:58,6,0,0,0,0,0,SYR,2023-01-03
3,UA,01/04/2023,1998,N893UA,ORD,21:17,21:31,113,110,14,21:26,5,0,0,0,0,0,SYR,2023-01-04
4,UA,01/05/2020,2012,N825UA,ORD,21:47,21:55,107,94,8,21:50,5,0,0,0,0,0,SYR,2020-01-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23609,WN,12/28/2023,3149,N462WN,MCO,13:00,13:08,160,147,8,13:05,3,0,0,0,0,0,SYR,2023-12-28
23610,WN,12/29/2023,3149,N551WN,MCO,13:00,12:46,160,150,-14,12:43,3,0,0,0,0,0,SYR,2023-12-29
23611,WN,12/30/2023,3208,N283WN,MCO,12:30,12:23,160,157,-7,12:14,9,0,0,0,0,0,SYR,2023-12-30
23612,WN,12/31/2022,1149,N7734H,MCO,14:05,14:12,160,147,7,14:10,2,0,0,0,0,0,SYR,2022-12-31
23613,WN,12/31/2023,3149,N8684F,MCO,14:10,13:58,160,152,-12,13:55,3,0,0,0,0,0,SYR,2023-12-31

In [7]:
arrivals_df.groupby(["Origin Airport", "Carrier Code"]).agg(count=('date', 'size'), 
    min_date=('date', 'min'), 
    max_date=('date', 'max'))

                             count   min_date   max_date
Origin Airport Carrier Code
JFK            9E             7462 2019-01-01 2023-12-31
               B6             2719 2019-01-01 2023-12-31
               OO                1 2021-05-10 2021-05-10
               YX              168 2019-01-01 2023-06-25
MCO            B6             1465 2019-01-01 2023-12-31
               F9             1060 2019-01-01 2023-12-31
               WN              182 2021-11-20 2023-12-31
ORD            AA              279 2019-04-02 2020-04-05
               EV               40 2019-01-13 2019-12-15
               F9               77 2019-04-30 2019-11-12
               MQ             4838 2019-01-01 2023-12-31
               OO             2347 2019-01-01 2023-12-20
               UA             1640 2019-01-07 2023-12-31
               YX             1356 2019-01-01 2023-12-31

In [69]:
departures_df.corr(numeric_only=True)

,Flight Number,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
Flight Number,1.000000,-0.316232,-0.252255,-0.102546,0.125368,-0.071520,-0.000675,-0.015385,-0.026537,-0.083576
Scheduled elapsed time (Minutes),-0.316232,1.000000,0.761815,0.079556,-0.074355,0.048123,0.009852,0.027272,0.031859,0.065694
Actual elapsed time (Minutes),-0.252255,0.761815,1.000000,0.093355,0.379531,0.072600,0.029859,0.189103,0.031205,0.088974
Departure delay (Minutes),-0.102546,0.079556,0.093355,1.000000,0.061610,0.689266,0.315787,0.263551,0.020990,0.677794
Taxi-Out time (Minutes),0.125368,-0.074355,0.379531,0.061610,1.000000,0.034105,0.054682,0.398884,0.001510,0.071830
Delay Carrier (Minutes),-0.071520,0.048123,0.072600,0.689266,0.034105,1.000000,-0.002195,0.033487,-0.004987,0.129774
Delay Weather (Minutes),-0.000675,0.009852,0.029859,0.315787,0.054682,-0.002195,1.000000,0.032766,-0.001357,0.040636
Delay National Aviation System (Minutes),-0.015385,0.027272,0.189103,0.263551,0.398884,0.033487,0.032766,1.000000,0.006024,0.067901
Delay Security (Minutes),-0.026537,0.031859,0.031205,0.020990,0.001510,-0.004987,-0.001357,0.006024,1.000000,0.028277
Delay Late Aircraft Arrival (Minutes),-0.083576,0.065694,0.088974,0.677794,0.071830,0.129774,0.040636,0.067901,0.028277,1.000000

In [24]:
departures_df = pd.read_csv("./data/modified/departures_jfk_mco_ord.csv")
departures_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Origin Airport
0,9E,01/01/2019,5391,N8943A,SYR,10:05,09:53,82,96,-12,10:13,20,0,0,0,0,0,JFK
1,9E,01/01/2020,5066,N980EV,SYR,10:05,09:51,92,72,-14,10:11,20,0,0,0,0,0,JFK
2,9E,01/01/2021,4851,N296PQ,SYR,17:29,17:21,76,68,-8,17:41,20,0,0,0,0,0,JFK
3,9E,01/01/2023,5190,N325PQ,SYR,21:10,21:05,91,68,-5,21:23,18,0,0,0,0,0,JFK
4,9E,01/02/2019,5391,N840AY,SYR,10:05,09:56,83,92,-9,10:27,31,0,0,0,0,0,JFK
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17458,F9,12/30/2023,3792,N341FR,SYR,16:35,16:28,171,178,-7,16:53,25,0,0,0,0,0,MCO
17459,F9,12/31/2020,1214,N232FR,SYR,14:15,14:10,176,157,-5,14:23,13,0,0,0,0,0,MCO
17460,F9,12/31/2021,1214,N347FR,SYR,17:01,16:56,166,169,-5,17:15,19,0,0,0,0,0,MCO
17461,F9,12/31/2022,1216,N235FR,SYR,07:55,07:48,169,144,-7,08:04,16,0,0,0,0,0,MCO
17462,F9,12/31/2023,3792,N605FR,SYR,07:30,07:27,172,170,-3,07:50,23,0,0,0,0,0,MCO

In [64]:
p = arrivals_df.groupby(["Carrier Code", "Date (MM/DD/YYYY)", "Flight Number"]).agg(count=('Flight Number', 'size'))
p["count"].unique()

array([1])

In [67]:
p[p["count"]==1]

                                              count
Carrier Code Date (MM/DD/YYYY) Flight Number
9E           01/01/2019        5391               1
             01/01/2020        5066               1
             01/01/2021        4851               1
             01/01/2023        5190               1
             01/02/2019        5391               1
...                                             ...
YX           12/29/2023        3719               1
             12/30/2019        5957               1
             12/30/2023        3719               1
             12/31/2022        4337               1
             12/31/2023        3719               1

[17464 rows x 1 columns]

In [45]:
p1 = arrivals_df.groupby(["Carrier Code", "Date (MM/DD/YYYY)", "Flight Number", "Scheduled Arrival Time"]).agg(count=('Flight Number', 'size')).reset_index()
p1["count"].unique()

array([2, 1])

In [46]:
p1[p1["count"]>1]

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Scheduled Arrival Time,count
0,9E,01/01/2019,5391,11:27,2
1,9E,01/01/2020,5066,11:37,2
2,9E,01/01/2021,4851,18:45,2
3,9E,01/01/2023,5190,22:41,2
4,9E,01/02/2019,5391,11:28,2
...,...,...,...,...,...
11765,MQ,12/30/2023,3324,22:34,2
11766,MQ,12/30/2023,4091,17:28,2
11767,MQ,12/31/2021,4316,18:15,2
11768,MQ,12/31/2023,4091,17:28,2
11769,MQ,12/31/2023,4134,11:19,2

In [52]:
for x, i in enumerate(p1.iloc[0]):
    print(p1.columns[x],"=", i, end = ") & (")

Carrier Code = 9E) & (Date (MM/DD/YYYY) = 01/01/2019) & (Flight Number = 5391) & (Scheduled Arrival Time = 11:27) & (count = 2) & (

In [68]:
merged_ad_df = pd.merge(arrivals_df, departures_df, on=['Date (MM/DD/YYYY)', 'Carrier Code', 'Flight Number'], how='inner')
# arrivals_df
merged_ad_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number_x,Origin Airport_x,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),...,Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes)_y,Delay Weather (Minutes)_y,Delay National Aviation System (Minutes)_y,Delay Security (Minutes)_y,Delay Late Aircraft Arrival (Minutes)_y,Origin Airport_y
0,UA,01/01/2023,2645,N23721,ORD,23:57,23:47,107,100,-10,...,100,-3,21:27,20,0,0,0,0,0,ORD
1,UA,01/02/2023,1998,N802UA,ORD,21:07,20:46,113,89,-21,...,89,3,18:34,17,0,0,0,0,0,ORD
2,UA,01/03/2023,1998,N854UA,ORD,21:07,21:04,113,111,-3,...,111,-1,18:44,31,0,0,0,0,0,ORD
3,UA,01/04/2023,1998,N893UA,ORD,21:17,21:31,113,110,14,...,110,17,19:14,33,0,0,0,0,0,ORD
4,UA,01/05/2020,2012,N825UA,ORD,21:47,21:55,107,94,8,...,94,21,19:35,14,0,0,0,0,0,ORD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17458,WN,12/28/2023,3149,N462WN,MCO,13:00,13:08,160,147,8,...,147,21,11:02,21,0,0,0,0,0,MCO
17459,WN,12/29/2023,3149,N551WN,MCO,13:00,12:46,160,150,-14,...,150,-4,10:32,16,0,0,0,0,0,MCO
17460,WN,12/30/2023,3208,N283WN,MCO,12:30,12:23,160,157,-7,...,157,-4,09:58,12,0,0,0,0,0,MCO
17461,WN,12/31/2022,1149,N7734H,MCO,14:05,14:12,160,147,7,...,147,20,11:54,9,0,0,0,0,0,MCO
17462,WN,12/31/2023,3149,N8684F,MCO,14:10,13:58,160,152,-12,...,152,-4,11:38,12,0,0,0,0,0,MCO

In [89]:
weather_df = pd.read_csv("./data/modified/weather_mco_ord_jfk_syr_tz.csv")
weather_df

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds,date_time
0,MCO,1546321980,N,69.0,29.0,2900.0,Partly Cloudy,67.0,69.0,93.0,...,69.0,190.0,S,8.0,0.0,Low,69.0,0.0,SCT,2019-01-01 00:53:00-05:00
1,MCO,1546325580,N,67.0,33.0,3300.0,Fair,65.0,67.0,93.0,...,67.0,200.0,SSW,6.0,0.0,Low,67.0,0.0,FEW,2019-01-01 01:53:00-05:00
2,MCO,1546329180,N,66.0,33.0,3300.0,Fair,64.0,66.0,93.0,...,66.0,210.0,SSW,3.0,0.0,Low,66.0,0.0,FEW,2019-01-01 02:53:00-05:00
3,MCO,1546331160,N,65.0,20.0,2000.0,Fog,64.0,65.0,97.0,...,65.0,190.0,S,3.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:26:00-05:00
4,MCO,1546331700,N,65.0,33.0,3300.0,Fair,65.0,65.0,100.0,...,65.0,NaN,CALM,0.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:35:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219795,SYR,1712523240,D,58.0,34.0,3400.0,Fair,26.0,58.0,30.0,...,58.0,340.0,NNW,12.0,0.0,Low,58.0,2.0,CLR,2024-04-07 16:54:00-04:00
219796,SYR,1712526840,D,57.0,34.0,3400.0,Fair,26.0,57.0,30.0,...,57.0,310.0,NW,15.0,0.0,Low,57.0,1.0,CLR,2024-04-07 17:54:00-04:00
219797,SYR,1712530440,D,56.0,34.0,3400.0,Fair,25.0,56.0,30.0,...,56.0,310.0,NW,12.0,0.0,Low,56.0,0.0,CLR,2024-04-07 18:54:00-04:00
219798,SYR,1712534040,N,50.0,33.0,3300.0,Fair,26.0,50.0,39.0,...,50.0,310.0,NW,7.0,0.0,Low,50.0,0.0,FEW,2024-04-07 19:54:00-04:00
219799,SYR,1712537640,N,47.0,33.0,3300.0,Fair,27.0,47.0,46.0,...,44.0,340.0,NNW,6.0,0.0,Low,44.0,0.0,FEW,2024-04-07 20:54:00-04:00

In [90]:
weather_df.dtypes

key                object
valid_time_gmt      int64
day_ind            object
temp              float64
wx_icon           float64
icon_extd         float64
wx_phrase          object
dewPt             float64
heat_index        float64
rh                float64
pressure          float64
vis               float64
wc                float64
wdir              float64
wdir_cardinal      object
wspd              float64
precip_hrly       float64
uv_desc            object
feels_like        float64
uv_index          float64
clds               object
date_time          object
dtype: object

In [91]:
weather_df["date_time"] = pd.to_datetime(weather_df["date_time"])
weather_df

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds,date_time
0,MCO,1546321980,N,69.0,29.0,2900.0,Partly Cloudy,67.0,69.0,93.0,...,69.0,190.0,S,8.0,0.0,Low,69.0,0.0,SCT,2019-01-01 00:53:00-05:00
1,MCO,1546325580,N,67.0,33.0,3300.0,Fair,65.0,67.0,93.0,...,67.0,200.0,SSW,6.0,0.0,Low,67.0,0.0,FEW,2019-01-01 01:53:00-05:00
2,MCO,1546329180,N,66.0,33.0,3300.0,Fair,64.0,66.0,93.0,...,66.0,210.0,SSW,3.0,0.0,Low,66.0,0.0,FEW,2019-01-01 02:53:00-05:00
3,MCO,1546331160,N,65.0,20.0,2000.0,Fog,64.0,65.0,97.0,...,65.0,190.0,S,3.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:26:00-05:00
4,MCO,1546331700,N,65.0,33.0,3300.0,Fair,65.0,65.0,100.0,...,65.0,NaN,CALM,0.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:35:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219795,SYR,1712523240,D,58.0,34.0,3400.0,Fair,26.0,58.0,30.0,...,58.0,340.0,NNW,12.0,0.0,Low,58.0,2.0,CLR,2024-04-07 16:54:00-04:00
219796,SYR,1712526840,D,57.0,34.0,3400.0,Fair,26.0,57.0,30.0,...,57.0,310.0,NW,15.0,0.0,Low,57.0,1.0,CLR,2024-04-07 17:54:00-04:00
219797,SYR,1712530440,D,56.0,34.0,3400.0,Fair,25.0,56.0,30.0,...,56.0,310.0,NW,12.0,0.0,Low,56.0,0.0,CLR,2024-04-07 18:54:00-04:00
219798,SYR,1712534040,N,50.0,33.0,3300.0,Fair,26.0,50.0,39.0,...,50.0,310.0,NW,7.0,0.0,Low,50.0,0.0,FEW,2024-04-07 19:54:00-04:00
219799,SYR,1712537640,N,47.0,33.0,3300.0,Fair,27.0,47.0,46.0,...,44.0,340.0,NNW,6.0,0.0,Low,44.0,0.0,FEW,2024-04-07 20:54:00-04:00

In [92]:
weather_df.isna().sum()

key                   0
valid_time_gmt        0
day_ind               0
temp                 10
wx_icon              14
icon_extd            14
wx_phrase            14
dewPt                19
heat_index           19
rh                   19
pressure             54
vis                  17
wc                  191
wdir              20154
wdir_cardinal       187
wspd                187
precip_hrly           0
uv_desc              56
feels_like           64
uv_index             56
clds                 20
date_time             0
dtype: int64

In [93]:
len(weather_df.columns)

22

In [94]:
w_corr = weather_df.corr(numeric_only=True)

In [95]:
w_corr_pairs = corr.unstack().abs().sort_values(ascending=False).drop_duplicates().head(15)
w_corr_pairs

valid_time_gmt  valid_time_gmt    1.000000
wc              feels_like        0.997847
temp            heat_index        0.997177
feels_like      temp              0.993734
                heat_index        0.993623
wc              temp              0.993555
                heat_index        0.988525
icon_extd       wx_icon           0.951590
dewPt           feels_like        0.921275
wc              dewPt             0.920601
dewPt           temp              0.918927
                heat_index        0.917293
icon_extd       vis               0.626319
vis             wx_icon           0.570689
uv_index        heat_index        0.427652
dtype: float64

In [96]:
w_corr_columns = set()
for pair in w_corr_pairs.index:
    w_corr_columns.add(pair[0])
    w_corr_columns.add(pair[1])
w_corr_columns

{'dewPt',
 'feels_like',
 'heat_index',
 'icon_extd',
 'temp',
 'uv_index',
 'valid_time_gmt',
 'vis',
 'wc',
 'wx_icon'}

In [15]:
w_cat_cols = weather_df.select_dtypes(include=['object'])
w_cat_cols

NameError: name 'weather_df' is not defined

In [98]:
weather_df.select_dtypes(include=['object'])

,key,day_ind,wx_phrase,wdir_cardinal,uv_desc,clds,date_time
0,MCO,N,Partly Cloudy,S,Low,SCT,2019-01-01 00:53:00-05:00
1,MCO,N,Fair,SSW,Low,FEW,2019-01-01 01:53:00-05:00
2,MCO,N,Fair,SSW,Low,FEW,2019-01-01 02:53:00-05:00
3,MCO,N,Fog,S,Low,FEW,2019-01-01 03:26:00-05:00
4,MCO,N,Fair,CALM,Low,FEW,2019-01-01 03:35:00-05:00
...,...,...,...,...,...,...,...
219795,SYR,D,Fair,NNW,Low,CLR,2024-04-07 16:54:00-04:00
219796,SYR,D,Fair,NW,Low,CLR,2024-04-07 17:54:00-04:00
219797,SYR,D,Fair,NW,Low,CLR,2024-04-07 18:54:00-04:00
219798,SYR,N,Fair,NW,Low,FEW,2024-04-07 19:54:00-04:00
219799,SYR,N,Fair,NNW,Low,FEW,2024-04-07 20:54:00-04:00

In [99]:
len(weather_cat_cols.columns.tolist() + list(weather_corr_columns))

17

In [100]:
test_df = pd.read_csv("../proj_prev/cleaned_adw_df_1.csv")
test_df

,Origin Airport_a,Scheduled Elapsed Time (Minutes)_a,Arrival Delay (Minutes)_a,Delay National Aviation System (Minutes)_a,Delay Security (Minutes)_a,Delay Late Aircraft Arrival (Minutes)_a,temp_a,wx_phrase_a,dewPt_a,heat_index_a,...,precip_hrly_d,snow_hrly_d,uv_desc_d,feels_like_d,uv_index_d,clds_d,Main_Carrier,Week_Category,A_Time_of_Day,Year
0,ORD,104.0,0.0,0.0,0.0,0.0,48.0,Cloudy,42.0,48.0,...,0.0,0.0,Low,21.0,0.0,OVC,AA,Midweek,Night,2019
1,JFK,70.0,-12.0,0.0,0.0,0.0,39.0,Cloudy,34.0,39.0,...,0.0,0.0,Low,54.0,0.0,BKN,B6,Midweek,Morning,2019
2,JFK,82.0,2.0,0.0,0.0,0.0,37.0,Cloudy,30.0,37.0,...,0.0,0.0,Low,59.0,0.0,BKN,DL,Midweek,Morning Peak,2019
3,ORD,104.0,63.0,21.0,0.0,0.0,36.0,Cloudy,29.0,36.0,...,0.0,0.0,Low,17.0,0.0,OVC,AA,Midweek,Morning Peak,2019
4,ORD,102.0,8.0,0.0,0.0,0.0,35.0,Snowy,28.0,35.0,...,0.0,0.0,Low,19.0,0.0,OVC,AA,Midweek,Afternoon,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17458,ORD,124.0,34.0,34.0,0.0,0.0,29.0,Snowy,26.0,29.0,...,0.0,0.0,Low,28.0,1.0,OVC,AA,Weekend,Evening Peak,2023
17459,ORD,106.0,102.0,0.0,0.0,68.0,29.0,Cloudy,26.0,29.0,...,0.0,0.0,Low,28.0,0.0,OVC,AA,Weekend,Evening Peak,2023
17460,MCO,175.0,-36.0,0.0,0.0,0.0,29.0,Cloudy,25.0,29.0,...,0.0,0.0,Low,67.0,1.0,SCT,B6,Weekend,Evening,2023
17461,ORD,114.0,-10.0,0.0,0.0,0.0,28.0,Cloudy,25.0,28.0,...,0.0,0.0,Low,22.0,0.0,OVC,UA,Weekend,Evening,2023
17462,JFK,105.0,-31.0,0.0,0.0,0.0,28.0,Cloudy,25.0,28.0,...,0.0,0.0,Low,37.0,0.0,OVC,DL,Weekend,Evening,2023

In [101]:
test_df.columns

Index(['Origin Airport_a', 'Scheduled Elapsed Time (Minutes)_a',
       'Arrival Delay (Minutes)_a',
       'Delay National Aviation System (Minutes)_a',
       'Delay Security (Minutes)_a', 'Delay Late Aircraft Arrival (Minutes)_a',
       'temp_a', 'wx_phrase_a', 'dewPt_a', 'heat_index_a', 'rh_a',
       'pressure_a', 'vis_a', 'wspd_a', 'precip_total_a', 'precip_hrly_a',
       'snow_hrly_a', 'uv_desc_a', 'feels_like_a', 'uv_index_a', 'clds_a',
       'Delay National Aviation System (Minutes)_d',
       'Delay Security (Minutes)_d', 'Delay Late Aircraft Arrival (Minutes)_d',
       'temp_d', 'wx_phrase_d', 'dewPt_d', 'heat_index_d', 'rh_d',
       'pressure_d', 'vis_d', 'wspd_d', 'precip_total_d', 'precip_hrly_d',
       'snow_hrly_d', 'uv_desc_d', 'feels_like_d', 'uv_index_d', 'clds_d',
       'Main_Carrier', 'Week_Category', 'A_Time_of_Day', 'Year'],
      dtype='object')

In [102]:
test_df[test_df["Origin Airport_a"]=="JFK"]["Main_Carrier"].unique()

array(['B6', 'DL', 'AA'], dtype=object)

In [103]:
test_df[test_df["Origin Airport_a"]=="ORD"]["Main_Carrier"].unique()

array(['AA', 'DL', 'UA', 'B6'], dtype=object)

In [104]:
test_df[test_df["Origin Airport_a"]=="MCO"]["Main_Carrier"].unique()

array(['B6', 'WN'], dtype=object)

In [105]:
test_df["Main_Carrier"].unique()

array(['AA', 'B6', 'DL', 'UA', 'WN'], dtype=object)

In [106]:
arrivals_df[arrivals_df["Origin Airport"]=="JFK"]

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport,date
2777,B6,01/01/2019,116,N373JB,JFK,07:53,07:41,70,64,-12,07:35,6,0,0,0,0,0,SYR,2019-01-01
2779,B6,01/01/2019,2516,N374JB,JFK,18:17,18:09,77,72,-8,18:05,4,0,0,0,0,0,SYR,2019-01-01
2780,B6,01/01/2020,116,N284JB,JFK,08:22,08:08,75,62,-14,08:05,3,0,0,0,0,0,SYR,2020-01-01
2782,B6,01/01/2020,2516,N294JB,JFK,20:50,20:31,80,71,-19,20:27,4,0,0,0,0,0,SYR,2020-01-01
2784,B6,01/01/2021,2516,N334JB,JFK,19:04,19:17,64,80,13,19:11,6,0,0,0,0,0,SYR,2021-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18376,YX,12/27/2019,5957,N871RW,JFK,18:02,17:41,93,74,-21,17:33,8,0,0,0,0,0,SYR,2019-12-27
18378,YX,12/28/2019,5957,N879RW,JFK,18:02,17:41,93,75,-21,17:36,5,0,0,0,0,0,SYR,2019-12-28
18380,YX,12/29/2019,5957,N874RW,JFK,18:02,17:38,93,75,-24,17:33,5,0,0,0,0,0,SYR,2019-12-29
18382,YX,12/30/2019,5957,N860RW,JFK,18:02,17:53,93,87,-9,17:41,12,0,0,0,0,0,SYR,2019-12-30
21968,OO,05/10/2021,4182,N921EV,JFK,16:25,21:22,90,65,297,21:17,5,283,0,0,0,14,SYR,2021-05-10

In [107]:
ini = pd.read_csv("./CIS_662 _INITIAL_Predictions.csv")
ini

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_early,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late
0,4/10/24,WEDNESDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
1,4/10/24,WEDNESDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
2,4/10/24,WEDNESDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN
3,4/10/24,WEDNESDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
4,4/10/24,WEDNESDAY,WN 5285,MCO,11:05 AM,1:45 PM,NaN,NaN,NaN,NaN
5,4/10/24,WEDNESDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN
6,4/11/24,THURSDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
7,4/11/24,THURSDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
8,4/11/24,THURSDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN
9,4/11/24,THURSDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
10,4/11/24,THURSDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN
11,4/11/24,THURSDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN
12,4/12/24,FRIDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
13,4/12/24,FRIDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
14,4/12/24,FRIDAY,B6 116,JFK,1:33 PM,2:50 PM,NaN,NaN,NaN,NaN
15,4/12/24,FRIDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
16,4/12/24,FRIDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN
17,4/12/24,FRIDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN
18,4/13/24,SATURDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
19,4/13/24,SATURDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
20,4/13/24,SATURDAY,B6 116,JFK,1:12 PM,2:30 PM,NaN,NaN,NaN,NaN
21,4/13/24,SATURDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
22,4/13/24,SATURDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN

In [108]:
fin = pd.read_csv("./CIS_662 _FINAL_Predictions.csv")
fin

,DATE,DAY,FLIGHT NUMBER,ORIGIN,DEPARTURE TIME,ARRIVAL TIME,ARRIVAL STATUS,ARRIVAL STATUS_Prev_flight_ontime,ARRIVAL STATUS_Prev_flight_late,Unnamed: 9
0,4/19/24,FRIDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
1,4/19/24,FRIDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
2,4/19/24,FRIDAY,B6 116,JFK,1:34 PM,2:51 PM,NaN,NaN,NaN,NaN
3,4/19/24,FRIDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
4,4/19/24,FRIDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN
5,4/19/24,FRIDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN
6,4/20/24,SATURDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
7,4/20/24,SATURDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
8,4/20/24,SATURDAY,B6 116,JFK,1:25 PM,2:41 PM,NaN,NaN,NaN,NaN
9,4/20/24,SATURDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
10,4/20/24,SATURDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN
11,4/21/24,SUNDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
12,4/21/24,SUNDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
13,4/21/24,SUNDAY,B6 116,JFK,1:35 PM,2:51 PM,NaN,NaN,NaN,NaN
14,4/21/24,SUNDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
15,4/21/24,SUNDAY,WN 5285,MCO,11:05 AM,1:50 PM,NaN,NaN,NaN,NaN
16,4/21/24,SUNDAY,B6 656,MCO,1:35 PM,4:25 PM,NaN,NaN,NaN,NaN
17,4/22/24,MONDAY,UA 1400,ORD,6:52 PM,9:47 PM,NaN,NaN,NaN,NaN
18,4/22/24,MONDAY,AA 3402,ORD,7:59 PM,10:52 PM,NaN,NaN,NaN,NaN
19,4/22/24,MONDAY,B6 116,JFK,1:35 PM,2:51 PM,NaN,NaN,NaN,NaN
20,4/22/24,MONDAY,DL 5182,JFK,2:55 PM,4:21 PM,NaN,NaN,NaN,NaN
21,4/22/24,MONDAY,WN 5285,MCO,11:35 AM,2:20 PM,NaN,NaN,NaN,NaN
22,4/22/24,MONDAY,B6 656,MCO,1:34 PM,4:25 PM,NaN,NaN,NaN,NaN

In [109]:
fin[fin["ORIGIN"]=="JFK"]["FLIGHT NUMBER"].unique()

array(['B6 116', 'DL 5182'], dtype=object)

In [110]:
fin[fin["ORIGIN"]=="ORD"]["FLIGHT NUMBER"].unique()

array(['UA 1400', 'AA 3402'], dtype=object)

In [111]:
fin[fin["ORIGIN"]=="MCO"]["FLIGHT NUMBER"].unique()

array(['WN 5285', 'B6 656'], dtype=object)

In [112]:
ini[ini["ORIGIN"]=="JFK"]["FLIGHT NUMBER"].unique()

array(['B6 116', 'DL 5182'], dtype=object)

In [113]:
ini[ini["ORIGIN"]=="ORD"]["FLIGHT NUMBER"].unique()

array(['UA 1400', 'AA 3402'], dtype=object)

In [114]:
ini[ini["ORIGIN"]=="MCO"]["FLIGHT NUMBER"].unique()

array(['WN 5285', 'B6 656'], dtype=object)

In [115]:
fin["FLIGHT NUMBER"].unique()

array(['UA 1400', 'AA 3402', 'B6 116', 'DL 5182', 'WN 5285', 'B6 656'],
      dtype=object)

In [116]:
ini["FLIGHT NUMBER"].unique()

array(['UA 1400', 'AA 3402', 'B6 116', 'DL 5182', 'WN 5285', 'B6 656'],
      dtype=object)

In [117]:
arrivals_df[arrivals_df["Origin Airport"]=="JFK"]["Carrier Code"].unique()

array(['B6', '9E', 'YX', 'OO'], dtype=object)

In [118]:
arrivals_df[arrivals_df["Origin Airport"]=="MCO"]["Carrier Code"].unique()

array(['F9', 'B6', 'WN'], dtype=object)

In [119]:
arrivals_df[arrivals_df["Origin Airport"]=="ORD"]["Carrier Code"].unique()

array(['UA', 'F9', 'MQ', 'EV', 'YX', 'AA', 'OO'], dtype=object)

In [120]:
test_df[test_df["Origin Airport_a"]=="JFK"]["Main_Carrier"].unique()

array(['B6', 'DL', 'AA'], dtype=object)

In [121]:
test_df[test_df["Origin Airport_a"]=="ORD"]["Main_Carrier"].unique()

array(['AA', 'DL', 'UA', 'B6'], dtype=object)

In [122]:
test_df[test_df["Origin Airport_a"]=="MCO"]["Main_Carrier"].unique()

array(['B6', 'WN'], dtype=object)

In [123]:
arrivals_df[(arrivals_df["Origin Airport"]=="JFK") & (arrivals_df["Carrier Code"]=="YX")]

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport,date
16863,YX,01/01/2019,6021,N871RW,JFK,18:01,18:05,91,75,4,17:59,6,0,0,0,0,0,SYR,2019-01-01
16864,YX,01/01/2020,5957,N809MD,JFK,18:02,17:35,93,68,-27,17:31,4,0,0,0,0,0,SYR,2020-01-01
16866,YX,01/02/2019,6021,N357FC,JFK,18:05,18:00,95,95,-5,17:37,23,0,0,0,0,0,SYR,2019-01-02
16867,YX,01/02/2020,5957,N203JQ,JFK,18:02,17:42,93,77,-20,17:35,7,0,0,0,0,0,SYR,2020-01-02
16869,YX,01/03/2019,6021,N860RW,JFK,18:05,17:48,95,87,-17,17:43,5,0,0,0,0,0,SYR,2019-01-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18374,YX,12/26/2019,5957,N818MD,JFK,18:02,17:29,93,64,-33,17:19,10,0,0,0,0,0,SYR,2019-12-26
18376,YX,12/27/2019,5957,N871RW,JFK,18:02,17:41,93,74,-21,17:33,8,0,0,0,0,0,SYR,2019-12-27
18378,YX,12/28/2019,5957,N879RW,JFK,18:02,17:41,93,75,-21,17:36,5,0,0,0,0,0,SYR,2019-12-28
18380,YX,12/29/2019,5957,N874RW,JFK,18:02,17:38,93,75,-24,17:33,5,0,0,0,0,0,SYR,2019-12-29
18382,YX,12/30/2019,5957,N860RW,JFK,18:02,17:53,93,87,-9,17:41,12,0,0,0,0,0,SYR,2019-12-30

In [124]:
arrivals_df[(arrivals_df["Origin Airport"]=="JFK") & (arrivals_df["Carrier Code"]=="YX")].sort_values(by="date", ascending=False)

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport,date
17652,YX,06/25/2023,5616,N206JQ,JFK,00:21,00:00,91,0,0,00:00,0,0,0,0,0,0,SYR,2023-06-25
17600,YX,06/18/2023,5689,N243JQ,JFK,00:21,00:02,91,76,-19,23:57,5,0,0,0,0,0,SYR,2023-06-18
17431,YX,05/24/2023,5859,N234JQ,JFK,15:03,14:24,94,61,-39,14:21,3,0,0,0,0,0,SYR,2023-05-24
17423,YX,05/23/2023,5859,N230JQ,JFK,15:03,14:32,94,74,-31,14:28,4,0,0,0,0,0,SYR,2023-05-23
17415,YX,05/22/2023,5859,N234JQ,JFK,15:03,14:36,94,72,-27,14:32,4,0,0,0,0,0,SYR,2023-05-22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18360,YX,12/21/2019,5957,N243JQ,JFK,18:02,17:35,93,75,-27,17:27,8,0,0,0,0,0,SYR,2019-12-21
16872,YX,01/04/2019,6021,N818MD,JFK,18:05,19:34,95,73,89,19:29,5,80,0,0,0,9,SYR,2019-01-04
16869,YX,01/03/2019,6021,N860RW,JFK,18:05,17:48,95,87,-17,17:43,5,0,0,0,0,0,SYR,2019-01-03
16866,YX,01/02/2019,6021,N357FC,JFK,18:05,18:00,95,95,-5,17:37,23,0,0,0,0,0,SYR,2019-01-02
16863,YX,01/01/2019,6021,N871RW,JFK,18:01,18:05,91,75,4,17:59,6,0,0,0,0,0,SYR,2019-01-01

   Origin Airport Carrier Code  count   min_date   max_date
0             JFK           9E   7462 2019-01-01 2023-12-31
1             JFK           B6   2719 2019-01-01 2023-12-31
2             JFK           OO      1 2021-05-10 2021-05-10
3             JFK           YX    168 2019-01-01 2023-06-25
4             MCO           B6   1465 2019-01-01 2023-12-31
5             MCO           F9   1060 2019-01-01 2023-12-31
6             MCO           WN    182 2021-11-20 2023-12-31
7             ORD           AA    279 2019-04-02 2020-04-05
8             ORD           EV     40 2019-01-13 2019-12-15
9             ORD           F9     77 2019-04-30 2019-11-12
10            ORD           MQ   4838 2019-01-01 2023-12-31
11            ORD           OO   2347 2019-01-01 2023-12-20
12            ORD           UA   1640 2019-01-07 2023-12-31
13            ORD           YX   1356 2019-01-01 2023-12-31

In [126]:
arrivals_df.corr(numeric_only=True)

,Flight Number,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes)
Flight Number,1.000000,-0.380345,-0.300128,-0.127040,0.064813,-0.074057,0.000543,-0.012183,-0.028525,-0.082793
Scheduled Elapsed Time (Minutes),-0.380345,1.000000,0.741808,0.103182,0.061524,0.050139,0.008705,0.022732,0.032713,0.065793
Actual Elapsed Time (Minutes),-0.300128,0.741808,1.000000,0.212693,0.268371,0.070176,0.030687,0.205801,0.030532,0.090162
Arrival Delay (Minutes),-0.127040,0.103182,0.212693,1.000000,0.086133,0.652360,0.338141,0.379631,0.021965,0.648886
Taxi-In time (Minutes),0.064813,0.061524,0.268371,0.086133,1.000000,0.016554,0.025231,0.109903,-0.007116,0.042411
Delay Carrier (Minutes),-0.074057,0.050139,0.070176,0.652360,0.016554,1.000000,-0.003456,0.030145,-0.003926,0.124976
Delay Weather (Minutes),0.000543,0.008705,0.030687,0.338141,0.025231,-0.003456,1.000000,0.036928,-0.001150,0.040799
Delay National Aviation System (Minutes),-0.012183,0.022732,0.205801,0.379631,0.109903,0.030145,0.036928,1.000000,0.005245,0.076973
Delay Security (Minutes),-0.028525,0.032713,0.030532,0.021965,-0.007116,-0.003926,-0.001150,0.005245,1.000000,0.026118
Delay Late Aircraft Arrival (Minutes),-0.082793,0.065793,0.090162,0.648886,0.042411,0.124976,0.040799,0.076973,0.026118,1.000000

In [129]:
weather_df.corr(numeric_only=True).abs().unstack().sort_values(ascending=False).drop_duplicates().head(15)

valid_time_gmt  valid_time_gmt    1.000000
wc              feels_like        0.997847
heat_index      temp              0.997177
feels_like      temp              0.993734
heat_index      feels_like        0.993623
wc              temp              0.993555
                heat_index        0.988525
icon_extd       wx_icon           0.951590
dewPt           feels_like        0.921275
wc              dewPt             0.920601
temp            dewPt             0.918927
heat_index      dewPt             0.917293
icon_extd       vis               0.626319
wx_icon         vis               0.570689
rh              icon_extd         0.440863
dtype: float64

In [82]:
weather_df.columns

Index(['key', 'valid_time_gmt', 'day_ind', 'temp', 'wx_icon', 'icon_extd',
       'wx_phrase', 'dewPt', 'heat_index', 'rh', 'pressure', 'vis', 'wc',
       'wdir', 'wdir_cardinal', 'wspd', 'precip_hrly', 'uv_desc', 'feels_like',
       'uv_index', 'clds', 'date_time'],
      dtype='object')