In [1]:
import pandas as pd

In [2]:
arrivals_df = pd.read_csv("./data/modified/arrivals_jfk_mco_ord.csv")
arrivals_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport
0,UA,01/01/2023,2645,N23721,ORD,23:57,23:47,107,100,-10,23:41,6,0,0,0,0,0,SYR
1,UA,01/02/2023,1998,N802UA,ORD,21:07,20:46,113,89,-21,20:43,3,0,0,0,0,0,SYR
2,UA,01/03/2023,1998,N854UA,ORD,21:07,21:04,113,111,-3,20:58,6,0,0,0,0,0,SYR
3,UA,01/04/2023,1998,N893UA,ORD,21:17,21:31,113,110,14,21:26,5,0,0,0,0,0,SYR
4,UA,01/05/2020,2012,N825UA,ORD,21:47,21:55,107,94,8,21:50,5,0,0,0,0,0,SYR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23629,EV,11/20/2019,4103,N609UX,ORD,09:19,09:17,109,108,-2,09:10,7,0,0,0,0,0,SYR
23630,EV,11/24/2019,4461,N609UX,ORD,12:03,11:58,108,107,-5,11:54,4,0,0,0,0,0,SYR
23631,EV,12/11/2019,4063,N607UX,ORD,12:23,12:39,108,105,16,12:34,5,10,0,0,0,6,SYR
23632,EV,12/14/2019,4486,N612UX,ORD,09:04,08:53,109,109,-11,08:44,9,0,0,0,0,0,SYR
23633,EV,12/15/2019,4486,N616UX,ORD,12:23,12:51,108,116,28,12:46,5,15,0,8,0,5,SYR

In [3]:
departures_df = pd.read_csv("./data/modified/departures.csv", index_col=0)
departures_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Destination Airport,Scheduled departure time,Actual departure time,Scheduled elapsed time (Minutes),Actual elapsed time (Minutes),Departure delay (Minutes),Wheels-off time,Taxi-Out time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Origin Airport
0,G4,01/02/2020,1737,241NV,SYR,06:30,06:29,176,167,-1,06:42,13,0,0,0,0,0,FLL
1,G4,01/03/2019,1720,226NV,SYR,06:50,06:49,182,167,-1,07:01,12,0,0,0,0,0,FLL
2,G4,01/03/2021,1744,245NV,SYR,16:25,17:40,178,168,75,17:53,13,0,0,0,0,65,FLL
3,G4,01/03/2022,962,222NV,SYR,06:15,06:15,176,175,0,06:30,15,0,0,0,0,0,FLL
4,G4,01/03/2023,523,234NV,SYR,06:30,10:34,182,170,244,10:51,17,232,0,0,0,0,FLL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56537,YX,12/16/2023,4312,N128HQ,SYR,19:45,19:39,213,198,-6,20:05,26,0,0,0,0,0,MIA
56538,YX,12/18/2021,5008,N127HQ,SYR,19:55,19:52,186,182,-3,20:10,18,0,0,0,0,0,MIA
56539,YX,12/23/2023,4371,N102HQ,SYR,19:44,19:42,206,187,-2,19:58,16,0,0,0,0,0,MIA
56540,YX,12/25/2021,5008,N425YX,SYR,19:55,19:49,186,194,-6,20:10,21,0,0,0,0,0,MIA
56541,YX,12/30/2023,4371,N444YX,SYR,19:44,19:38,206,185,-6,19:58,20,0,0,0,0,0,MIA

In [4]:
weather_df = pd.read_csv("./data/modified/weather_mco_ord_jfk_syr_tz.csv")
weather_df

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds,date_time
0,MCO,1546321980,N,69.0,29.0,2900.0,Partly Cloudy,67.0,69.0,93.0,...,69.0,190.0,S,8.0,0.0,Low,69.0,0.0,SCT,2019-01-01 00:53:00-05:00
1,MCO,1546325580,N,67.0,33.0,3300.0,Fair,65.0,67.0,93.0,...,67.0,200.0,SSW,6.0,0.0,Low,67.0,0.0,FEW,2019-01-01 01:53:00-05:00
2,MCO,1546329180,N,66.0,33.0,3300.0,Fair,64.0,66.0,93.0,...,66.0,210.0,SSW,3.0,0.0,Low,66.0,0.0,FEW,2019-01-01 02:53:00-05:00
3,MCO,1546331160,N,65.0,20.0,2000.0,Fog,64.0,65.0,97.0,...,65.0,190.0,S,3.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:26:00-05:00
4,MCO,1546331700,N,65.0,33.0,3300.0,Fair,65.0,65.0,100.0,...,65.0,NaN,CALM,0.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:35:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219795,SYR,1712523240,D,58.0,34.0,3400.0,Fair,26.0,58.0,30.0,...,58.0,340.0,NNW,12.0,0.0,Low,58.0,2.0,CLR,2024-04-07 16:54:00-04:00
219796,SYR,1712526840,D,57.0,34.0,3400.0,Fair,26.0,57.0,30.0,...,57.0,310.0,NW,15.0,0.0,Low,57.0,1.0,CLR,2024-04-07 17:54:00-04:00
219797,SYR,1712530440,D,56.0,34.0,3400.0,Fair,25.0,56.0,30.0,...,56.0,310.0,NW,12.0,0.0,Low,56.0,0.0,CLR,2024-04-07 18:54:00-04:00
219798,SYR,1712534040,N,50.0,33.0,3300.0,Fair,26.0,50.0,39.0,...,50.0,310.0,NW,7.0,0.0,Low,50.0,0.0,FEW,2024-04-07 19:54:00-04:00
219799,SYR,1712537640,N,47.0,33.0,3300.0,Fair,27.0,47.0,46.0,...,44.0,340.0,NNW,6.0,0.0,Low,44.0,0.0,FEW,2024-04-07 20:54:00-04:00

In [6]:
weather_df.isna().sum()

key                   0
valid_time_gmt        0
day_ind               0
temp                 10
wx_icon              14
icon_extd            14
wx_phrase            14
dewPt                19
heat_index           19
rh                   19
pressure             54
vis                  17
wc                  191
wdir              20154
wdir_cardinal       187
wspd                187
precip_hrly           0
uv_desc              56
feels_like           64
uv_index             56
clds                 20
date_time             0
dtype: int64

In [9]:
len(weather_df.columns)

21

In [10]:
weather_df.corr(numeric_only=True).unstack().sort_values(ascending=False).drop_duplicates()[:15]

valid_time_gmt  valid_time_gmt    1.000000
wc              feels_like        0.997847
temp            heat_index        0.997177
feels_like      temp              0.993734
                heat_index        0.993623
wc              temp              0.993555
                heat_index        0.988525
icon_extd       wx_icon           0.951590
dewPt           feels_like        0.921275
wc              dewPt             0.920601
dewPt           temp              0.918927
                heat_index        0.917293
icon_extd       vis               0.626319
vis             wx_icon           0.570689
uv_index        heat_index        0.427652
dtype: float64

In [11]:
weather_df

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,vis,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds
0,KMCO,1546321980,N,69.0,29.0,2900.0,Partly Cloudy,67.0,69.0,93.0,...,9.0,69.0,190.0,S,8.0,0.0,Low,69.0,0.0,SCT
1,KMCO,1546325580,N,67.0,33.0,3300.0,Fair,65.0,67.0,93.0,...,6.0,67.0,200.0,SSW,6.0,0.0,Low,67.0,0.0,FEW
2,KMCO,1546329180,N,66.0,33.0,3300.0,Fair,64.0,66.0,93.0,...,8.0,66.0,210.0,SSW,3.0,0.0,Low,66.0,0.0,FEW
3,KMCO,1546331160,N,65.0,20.0,2000.0,Fog,64.0,65.0,97.0,...,1.0,65.0,190.0,S,3.0,0.0,Low,65.0,0.0,FEW
4,KMCO,1546331700,N,65.0,33.0,3300.0,Fair,65.0,65.0,100.0,...,7.0,65.0,NaN,CALM,0.0,0.0,Low,65.0,0.0,FEW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219795,KSYR,1712523240,D,58.0,34.0,3400.0,Fair,26.0,58.0,30.0,...,10.0,58.0,340.0,NNW,12.0,0.0,Low,58.0,2.0,CLR
219796,KSYR,1712526840,D,57.0,34.0,3400.0,Fair,26.0,57.0,30.0,...,10.0,57.0,310.0,NW,15.0,0.0,Low,57.0,1.0,CLR
219797,KSYR,1712530440,D,56.0,34.0,3400.0,Fair,25.0,56.0,30.0,...,10.0,56.0,310.0,NW,12.0,0.0,Low,56.0,0.0,CLR
219798,KSYR,1712534040,N,50.0,33.0,3300.0,Fair,26.0,50.0,39.0,...,10.0,50.0,310.0,NW,7.0,0.0,Low,50.0,0.0,FEW
219799,KSYR,1712537640,N,47.0,33.0,3300.0,Fair,27.0,47.0,46.0,...,10.0,44.0,340.0,NNW,6.0,0.0,Low,44.0,0.0,FEW

In [12]:
weather_df["key"] = weather_df["key"].str[1:]
weather_df

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,vis,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds
0,MCO,1546321980,N,69.0,29.0,2900.0,Partly Cloudy,67.0,69.0,93.0,...,9.0,69.0,190.0,S,8.0,0.0,Low,69.0,0.0,SCT
1,MCO,1546325580,N,67.0,33.0,3300.0,Fair,65.0,67.0,93.0,...,6.0,67.0,200.0,SSW,6.0,0.0,Low,67.0,0.0,FEW
2,MCO,1546329180,N,66.0,33.0,3300.0,Fair,64.0,66.0,93.0,...,8.0,66.0,210.0,SSW,3.0,0.0,Low,66.0,0.0,FEW
3,MCO,1546331160,N,65.0,20.0,2000.0,Fog,64.0,65.0,97.0,...,1.0,65.0,190.0,S,3.0,0.0,Low,65.0,0.0,FEW
4,MCO,1546331700,N,65.0,33.0,3300.0,Fair,65.0,65.0,100.0,...,7.0,65.0,NaN,CALM,0.0,0.0,Low,65.0,0.0,FEW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219795,SYR,1712523240,D,58.0,34.0,3400.0,Fair,26.0,58.0,30.0,...,10.0,58.0,340.0,NNW,12.0,0.0,Low,58.0,2.0,CLR
219796,SYR,1712526840,D,57.0,34.0,3400.0,Fair,26.0,57.0,30.0,...,10.0,57.0,310.0,NW,15.0,0.0,Low,57.0,1.0,CLR
219797,SYR,1712530440,D,56.0,34.0,3400.0,Fair,25.0,56.0,30.0,...,10.0,56.0,310.0,NW,12.0,0.0,Low,56.0,0.0,CLR
219798,SYR,1712534040,N,50.0,33.0,3300.0,Fair,26.0,50.0,39.0,...,10.0,50.0,310.0,NW,7.0,0.0,Low,50.0,0.0,FEW
219799,SYR,1712537640,N,47.0,33.0,3300.0,Fair,27.0,47.0,46.0,...,10.0,44.0,340.0,NNW,6.0,0.0,Low,44.0,0.0,FEW

In [13]:
weather_df["date_time"] = pd.to_datetime(weather_df["valid_time_gmt"], unit='s', utc=True).dt.tz_convert('America/New_York')
weather_df

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds,date_time
0,MCO,1546321980,N,69.0,29.0,2900.0,Partly Cloudy,67.0,69.0,93.0,...,69.0,190.0,S,8.0,0.0,Low,69.0,0.0,SCT,2019-01-01 00:53:00-05:00
1,MCO,1546325580,N,67.0,33.0,3300.0,Fair,65.0,67.0,93.0,...,67.0,200.0,SSW,6.0,0.0,Low,67.0,0.0,FEW,2019-01-01 01:53:00-05:00
2,MCO,1546329180,N,66.0,33.0,3300.0,Fair,64.0,66.0,93.0,...,66.0,210.0,SSW,3.0,0.0,Low,66.0,0.0,FEW,2019-01-01 02:53:00-05:00
3,MCO,1546331160,N,65.0,20.0,2000.0,Fog,64.0,65.0,97.0,...,65.0,190.0,S,3.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:26:00-05:00
4,MCO,1546331700,N,65.0,33.0,3300.0,Fair,65.0,65.0,100.0,...,65.0,NaN,CALM,0.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:35:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219795,SYR,1712523240,D,58.0,34.0,3400.0,Fair,26.0,58.0,30.0,...,58.0,340.0,NNW,12.0,0.0,Low,58.0,2.0,CLR,2024-04-07 16:54:00-04:00
219796,SYR,1712526840,D,57.0,34.0,3400.0,Fair,26.0,57.0,30.0,...,57.0,310.0,NW,15.0,0.0,Low,57.0,1.0,CLR,2024-04-07 17:54:00-04:00
219797,SYR,1712530440,D,56.0,34.0,3400.0,Fair,25.0,56.0,30.0,...,56.0,310.0,NW,12.0,0.0,Low,56.0,0.0,CLR,2024-04-07 18:54:00-04:00
219798,SYR,1712534040,N,50.0,33.0,3300.0,Fair,26.0,50.0,39.0,...,50.0,310.0,NW,7.0,0.0,Low,50.0,0.0,FEW,2024-04-07 19:54:00-04:00
219799,SYR,1712537640,N,47.0,33.0,3300.0,Fair,27.0,47.0,46.0,...,44.0,340.0,NNW,6.0,0.0,Low,44.0,0.0,FEW,2024-04-07 20:54:00-04:00

In [14]:
weather_df[weather_df["key"]=="ORD"]

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds,date_time
52982,ORD,1546325460,N,34.0,26.0,2600.0,Cloudy,32.0,34.0,92.0,...,27.0,330.0,NNW,8.0,0.0,Low,27.0,0.0,OVC,2019-01-01 01:51:00-05:00
52983,ORD,1546329060,N,33.0,26.0,2600.0,Cloudy,31.0,33.0,92.0,...,25.0,320.0,NW,10.0,0.0,Low,25.0,0.0,OVC,2019-01-01 02:51:00-05:00
52984,ORD,1546330140,N,33.0,26.0,2600.0,Cloudy,31.0,33.0,92.0,...,24.0,320.0,NW,13.0,0.0,Low,24.0,0.0,OVC,2019-01-01 03:09:00-05:00
52985,ORD,1546330620,N,33.0,14.0,1601.0,Light Snow,31.0,33.0,92.0,...,25.0,320.0,NW,9.0,0.0,Low,25.0,0.0,OVC,2019-01-01 03:17:00-05:00
52986,ORD,1546332660,N,32.0,14.0,1601.0,Light Snow,31.0,32.0,96.0,...,26.0,330.0,NNW,7.0,0.0,Low,26.0,0.0,OVC,2019-01-01 03:51:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109986,ORD,1712525220,D,47.0,11.0,1201.0,Light Rain,44.0,47.0,90.0,...,42.0,120.0,ESE,12.0,0.1,Low,42.0,1.0,OVC,2024-04-07 17:27:00-04:00
109987,ORD,1712526660,D,48.0,26.0,2600.0,Cloudy,44.0,48.0,86.0,...,43.0,130.0,SE,10.0,0.1,Low,43.0,1.0,OVC,2024-04-07 17:51:00-04:00
109988,ORD,1712530260,D,49.0,28.0,2800.0,Mostly Cloudy,45.0,49.0,86.0,...,44.0,120.0,ESE,13.0,0.0,Low,44.0,0.0,BKN,2024-04-07 18:51:00-04:00
109989,ORD,1712533860,D,50.0,28.0,2800.0,Mostly Cloudy,44.0,50.0,80.0,...,50.0,120.0,ESE,12.0,0.0,Low,50.0,0.0,BKN,2024-04-07 19:51:00-04:00
109990,ORD,1712537460,N,49.0,27.0,2700.0,Mostly Cloudy,43.0,49.0,80.0,...,44.0,110.0,ESE,13.0,0.0,Low,44.0,0.0,BKN,2024-04-07 20:51:00-04:00

In [21]:
# weather_df[weather_df["key"]=="ORD"]["date_time"] = weather_df[weather_df["key"]=="ORD"]["date_time"] - pd.Timedelta(hours=1)
weather_df.loc[weather_df["key"]=="ORD", 'date_time'] -= pd.Timedelta(hours=1)

In [22]:
weather_df[weather_df["key"]=="ORD"]

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds,date_time
52982,ORD,1546325460,N,34.0,26.0,2600.0,Cloudy,32.0,34.0,92.0,...,27.0,330.0,NNW,8.0,0.0,Low,27.0,0.0,OVC,2019-01-01 00:51:00-05:00
52983,ORD,1546329060,N,33.0,26.0,2600.0,Cloudy,31.0,33.0,92.0,...,25.0,320.0,NW,10.0,0.0,Low,25.0,0.0,OVC,2019-01-01 01:51:00-05:00
52984,ORD,1546330140,N,33.0,26.0,2600.0,Cloudy,31.0,33.0,92.0,...,24.0,320.0,NW,13.0,0.0,Low,24.0,0.0,OVC,2019-01-01 02:09:00-05:00
52985,ORD,1546330620,N,33.0,14.0,1601.0,Light Snow,31.0,33.0,92.0,...,25.0,320.0,NW,9.0,0.0,Low,25.0,0.0,OVC,2019-01-01 02:17:00-05:00
52986,ORD,1546332660,N,32.0,14.0,1601.0,Light Snow,31.0,32.0,96.0,...,26.0,330.0,NNW,7.0,0.0,Low,26.0,0.0,OVC,2019-01-01 02:51:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109986,ORD,1712525220,D,47.0,11.0,1201.0,Light Rain,44.0,47.0,90.0,...,42.0,120.0,ESE,12.0,0.1,Low,42.0,1.0,OVC,2024-04-07 16:27:00-04:00
109987,ORD,1712526660,D,48.0,26.0,2600.0,Cloudy,44.0,48.0,86.0,...,43.0,130.0,SE,10.0,0.1,Low,43.0,1.0,OVC,2024-04-07 16:51:00-04:00
109988,ORD,1712530260,D,49.0,28.0,2800.0,Mostly Cloudy,45.0,49.0,86.0,...,44.0,120.0,ESE,13.0,0.0,Low,44.0,0.0,BKN,2024-04-07 17:51:00-04:00
109989,ORD,1712533860,D,50.0,28.0,2800.0,Mostly Cloudy,44.0,50.0,80.0,...,50.0,120.0,ESE,12.0,0.0,Low,50.0,0.0,BKN,2024-04-07 18:51:00-04:00
109990,ORD,1712537460,N,49.0,27.0,2700.0,Mostly Cloudy,43.0,49.0,80.0,...,44.0,110.0,ESE,13.0,0.0,Low,44.0,0.0,BKN,2024-04-07 19:51:00-04:00

In [18]:
weather_df

,key,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,wx_phrase,dewPt,heat_index,rh,...,wc,wdir,wdir_cardinal,wspd,precip_hrly,uv_desc,feels_like,uv_index,clds,date_time
0,MCO,1546321980,N,69.0,29.0,2900.0,Partly Cloudy,67.0,69.0,93.0,...,69.0,190.0,S,8.0,0.0,Low,69.0,0.0,SCT,2019-01-01 00:53:00-05:00
1,MCO,1546325580,N,67.0,33.0,3300.0,Fair,65.0,67.0,93.0,...,67.0,200.0,SSW,6.0,0.0,Low,67.0,0.0,FEW,2019-01-01 01:53:00-05:00
2,MCO,1546329180,N,66.0,33.0,3300.0,Fair,64.0,66.0,93.0,...,66.0,210.0,SSW,3.0,0.0,Low,66.0,0.0,FEW,2019-01-01 02:53:00-05:00
3,MCO,1546331160,N,65.0,20.0,2000.0,Fog,64.0,65.0,97.0,...,65.0,190.0,S,3.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:26:00-05:00
4,MCO,1546331700,N,65.0,33.0,3300.0,Fair,65.0,65.0,100.0,...,65.0,NaN,CALM,0.0,0.0,Low,65.0,0.0,FEW,2019-01-01 03:35:00-05:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
219795,SYR,1712523240,D,58.0,34.0,3400.0,Fair,26.0,58.0,30.0,...,58.0,340.0,NNW,12.0,0.0,Low,58.0,2.0,CLR,2024-04-07 16:54:00-04:00
219796,SYR,1712526840,D,57.0,34.0,3400.0,Fair,26.0,57.0,30.0,...,57.0,310.0,NW,15.0,0.0,Low,57.0,1.0,CLR,2024-04-07 17:54:00-04:00
219797,SYR,1712530440,D,56.0,34.0,3400.0,Fair,25.0,56.0,30.0,...,56.0,310.0,NW,12.0,0.0,Low,56.0,0.0,CLR,2024-04-07 18:54:00-04:00
219798,SYR,1712534040,N,50.0,33.0,3300.0,Fair,26.0,50.0,39.0,...,50.0,310.0,NW,7.0,0.0,Low,50.0,0.0,FEW,2024-04-07 19:54:00-04:00
219799,SYR,1712537640,N,47.0,33.0,3300.0,Fair,27.0,47.0,46.0,...,44.0,340.0,NNW,6.0,0.0,Low,44.0,0.0,FEW,2024-04-07 20:54:00-04:00

In [71]:
weather_df.select_dtypes(include=['object'])

,key,day_ind,wx_phrase,wdir_cardinal,uv_desc,clds,est_time,est_date
0,MCO,N,Partly Cloudy,S,Low,SCT,00:53:00,2019-01-01
1,MCO,N,Fair,SSW,Low,FEW,01:53:00,2019-01-01
2,MCO,N,Fair,SSW,Low,FEW,02:53:00,2019-01-01
3,MCO,N,Fog,S,Low,FEW,03:26:00,2019-01-01
4,MCO,N,Fair,CALM,Low,FEW,03:35:00,2019-01-01
...,...,...,...,...,...,...,...,...
219795,SYR,D,Fair,NNW,Low,CLR,16:54:00,2024-04-07
219796,SYR,D,Fair,NW,Low,CLR,17:54:00,2024-04-07
219797,SYR,D,Fair,NW,Low,CLR,18:54:00,2024-04-07
219798,SYR,N,Fair,NW,Low,FEW,19:54:00,2024-04-07
219799,SYR,N,Fair,NNW,Low,FEW,20:54:00,2024-04-07

In [66]:
weather_df.to_csv("./data/modified/removed_nan_weather.csv")

In [44]:
temp_df = pd.read_csv("../proj_prev/cleaned_adw_df_1.csv")
temp_df

,Origin Airport_a,Scheduled Elapsed Time (Minutes)_a,Arrival Delay (Minutes)_a,Delay National Aviation System (Minutes)_a,Delay Security (Minutes)_a,Delay Late Aircraft Arrival (Minutes)_a,temp_a,wx_phrase_a,dewPt_a,heat_index_a,...,precip_hrly_d,snow_hrly_d,uv_desc_d,feels_like_d,uv_index_d,clds_d,Main_Carrier,Week_Category,A_Time_of_Day,Year
0,ORD,104.0,0.0,0.0,0.0,0.0,48.0,Cloudy,42.0,48.0,...,0.0,0.0,Low,21.0,0.0,OVC,AA,Midweek,Night,2019
1,JFK,70.0,-12.0,0.0,0.0,0.0,39.0,Cloudy,34.0,39.0,...,0.0,0.0,Low,54.0,0.0,BKN,B6,Midweek,Morning,2019
2,JFK,82.0,2.0,0.0,0.0,0.0,37.0,Cloudy,30.0,37.0,...,0.0,0.0,Low,59.0,0.0,BKN,DL,Midweek,Morning Peak,2019
3,ORD,104.0,63.0,21.0,0.0,0.0,36.0,Cloudy,29.0,36.0,...,0.0,0.0,Low,17.0,0.0,OVC,AA,Midweek,Morning Peak,2019
4,ORD,102.0,8.0,0.0,0.0,0.0,35.0,Snowy,28.0,35.0,...,0.0,0.0,Low,19.0,0.0,OVC,AA,Midweek,Afternoon,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17458,ORD,124.0,34.0,34.0,0.0,0.0,29.0,Snowy,26.0,29.0,...,0.0,0.0,Low,28.0,1.0,OVC,AA,Weekend,Evening Peak,2023
17459,ORD,106.0,102.0,0.0,0.0,68.0,29.0,Cloudy,26.0,29.0,...,0.0,0.0,Low,28.0,0.0,OVC,AA,Weekend,Evening Peak,2023
17460,MCO,175.0,-36.0,0.0,0.0,0.0,29.0,Cloudy,25.0,29.0,...,0.0,0.0,Low,67.0,1.0,SCT,B6,Weekend,Evening,2023
17461,ORD,114.0,-10.0,0.0,0.0,0.0,28.0,Cloudy,25.0,28.0,...,0.0,0.0,Low,22.0,0.0,OVC,UA,Weekend,Evening,2023
17462,JFK,105.0,-31.0,0.0,0.0,0.0,28.0,Cloudy,25.0,28.0,...,0.0,0.0,Low,37.0,0.0,OVC,DL,Weekend,Evening,2023

In [45]:
temp_df.columns

Index(['Origin Airport_a', 'Scheduled Elapsed Time (Minutes)_a',
       'Arrival Delay (Minutes)_a',
       'Delay National Aviation System (Minutes)_a',
       'Delay Security (Minutes)_a', 'Delay Late Aircraft Arrival (Minutes)_a',
       'temp_a', 'wx_phrase_a', 'dewPt_a', 'heat_index_a', 'rh_a',
       'pressure_a', 'vis_a', 'wspd_a', 'precip_total_a', 'precip_hrly_a',
       'snow_hrly_a', 'uv_desc_a', 'feels_like_a', 'uv_index_a', 'clds_a',
       'Delay National Aviation System (Minutes)_d',
       'Delay Security (Minutes)_d', 'Delay Late Aircraft Arrival (Minutes)_d',
       'temp_d', 'wx_phrase_d', 'dewPt_d', 'heat_index_d', 'rh_d',
       'pressure_d', 'vis_d', 'wspd_d', 'precip_total_d', 'precip_hrly_d',
       'snow_hrly_d', 'uv_desc_d', 'feels_like_d', 'uv_index_d', 'clds_d',
       'Main_Carrier', 'Week_Category', 'A_Time_of_Day', 'Year'],
      dtype='object')

In [63]:
l = ['temp_a', 'wx_phrase_a', 'dewPt_a', 'heat_index_a', 'rh_a',
       'pressure_a', 'vis_a', 'wspd_a', 'precip_total_a', 'precip_hrly_a',
       'snow_hrly_a', 'uv_desc_a', 'feels_like_a', 'uv_index_a', 'clds_a']

In [64]:
len(l)

15

In [ ]:

# Filter flight data for Syracuse arrivals
syracuse_flights = flight_data[flight_data['Destination'] == 'Syracuse']

# Merge weather data for Syracuse based on date
merged_data = pd.merge(syracuse_flights, weather_data, left_on=['Date', 'Scheduled Arrival Time'], right_on=['Date', 'Scheduled Departure Time'])

# Now merged_data contains the flight data for Syracuse with corresponding weather data

In [46]:
weather_df.columns

Index(['key', 'class', 'expire_time_gmt', 'obs_id', 'obs_name',
       'valid_time_gmt', 'day_ind', 'temp', 'wx_icon', 'icon_extd',
       'wx_phrase', 'dewPt', 'heat_index', 'rh', 'pressure', 'vis', 'wc',
       'wdir', 'wdir_cardinal', 'wspd', 'precip_hrly', 'uv_desc', 'feels_like',
       'uv_index', 'clds', 'est_time', 'est_date'],
      dtype='object')

In [60]:
t2_df = pd.read_csv("./merged.csv")
t2_df

,Date (MM/DD/YYYY),Origin Airport,Actual Arrival Time,Arrival Delay (Minutes),Actual departure time,Departure delay (Minutes),Flight_Number,Scheduled_Departure_Datetime,Scheduled_Arrival_Datetime
0,01/01/2019,ORD,00:54,0.0,22:09,-1,MQ 4011,2019-01-01 22:10:00,2019-01-01 00:54:00
1,01/01/2019,ORD,00:54,0.0,22:09,-1,MQ 4011,2019-01-01 22:10:00,2019-01-01 00:54:00
2,01/01/2019,JFK,07:41,-12.0,06:37,-6,B6 116,2019-01-01 06:43:00,2019-01-01 07:53:00
3,01/01/2019,JFK,11:29,2.0,09:53,-12,9E 5391,2019-01-01 10:05:00,2019-01-01 11:27:00
4,01/01/2019,JFK,11:29,2.0,09:53,-12,9E 5391,2019-01-01 10:05:00,2019-01-01 11:27:00
...,...,...,...,...,...,...,...,...,...
23470,12/31/2023,ORD,19:10,102.0,16:25,103,MQ 4091,2023-12-31 14:42:00,2023-12-31 17:28:00
23471,12/31/2023,MCO,18:51,-36.0,16:23,-9,B6 656,2023-12-31 16:32:00,2023-12-31 19:27:00
23472,12/31/2023,ORD,20:59,-10.0,18:06,-9,UA 1983,2023-12-31 18:15:00,2023-12-31 21:09:00
23473,12/31/2023,JFK,20:54,-31.0,19:36,-4,9E 4988,2023-12-31 19:40:00,2023-12-31 21:25:00
23474,12/31/2023,JFK,20:54,-31.0,19:36,-4,9E 4988,2023-12-31 19:40:00,2023-12-31 21:25:00

In [61]:
t2_df.dtypes

Date (MM/DD/YYYY)                object
Origin Airport                   object
Actual Arrival Time              object
Arrival Delay (Minutes)         float64
Actual departure time            object
Departure delay (Minutes)         int64
Flight_Number                    object
Scheduled_Departure_Datetime     object
Scheduled_Arrival_Datetime       object
dtype: object

In [62]:
weather_df.dtypes

key                object
valid_time_gmt      int64
day_ind            object
temp              float64
wx_icon           float64
icon_extd         float64
wx_phrase          object
dewPt             float64
heat_index        float64
rh                float64
pressure          float64
vis               float64
wc                float64
wdir              float64
wdir_cardinal      object
wspd              float64
precip_hrly       float64
uv_desc            object
feels_like        float64
uv_index          float64
clds               object
est_time           object
est_date           object
dtype: object

In [84]:
arrivals_df

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport
0,UA,01/01/2022,1282,N4901U,IAD,23:10,00:01,70,76,51,23:55,6,23,0,6,0,22,SYR
1,UA,01/01/2023,604,N814UA,DEN,14:58,14:52,193,177,-6,14:48,4,0,0,0,0,0,SYR
2,UA,01/01/2023,2488,N38458,EWR,23:14,23:15,75,62,1,23:10,5,0,0,0,0,0,SYR
3,UA,01/01/2023,2645,N23721,ORD,23:57,23:47,107,100,-10,23:41,6,0,0,0,0,0,SYR
4,UA,01/02/2022,1282,N4901U,IAD,23:10,23:27,70,64,17,23:19,8,17,0,0,0,0,SYR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69503,EV,12/16/2019,3977,N16976,EWR,13:21,14:06,74,61,45,14:01,5,45,0,0,0,0,SYR
69504,EV,12/17/2019,3977,N13978,EWR,13:21,13:53,74,113,32,13:41,12,0,0,32,0,0,SYR
69505,EV,12/18/2019,3977,N26545,EWR,13:21,14:46,74,76,85,14:37,9,83,0,2,0,0,SYR
69506,EV,12/22/2019,4388,N13903,EWR,23:13,23:06,76,67,-7,23:00,6,0,0,0,0,0,SYR
69507,EV,12/30/2019,3205,N14902,EWR,18:18,18:09,79,79,-9,18:04,5,0,0,0,0,0,SYR

In [85]:
arrivals_df[arrivals_df['Origin Airport'].isin(['ORD', 'JFK', "MCO"])]

,Carrier Code,Date (MM/DD/YYYY),Flight Number,Tail Number,Origin Airport,Scheduled Arrival Time,Actual Arrival Time,Scheduled Elapsed Time (Minutes),Actual Elapsed Time (Minutes),Arrival Delay (Minutes),Wheels-on Time,Taxi-In time (Minutes),Delay Carrier (Minutes),Delay Weather (Minutes),Delay National Aviation System (Minutes),Delay Security (Minutes),Delay Late Aircraft Arrival (Minutes),Destination Airport
3,UA,01/01/2023,2645,N23721,ORD,23:57,23:47,107,100,-10,23:41,6,0,0,0,0,0,SYR
7,UA,01/02/2023,1998,N802UA,ORD,21:07,20:46,113,89,-21,20:43,3,0,0,0,0,0,SYR
10,UA,01/03/2023,1998,N854UA,ORD,21:07,21:04,113,111,-3,20:58,6,0,0,0,0,0,SYR
13,UA,01/04/2023,1998,N893UA,ORD,21:17,21:31,113,110,14,21:26,5,0,0,0,0,0,SYR
14,UA,01/05/2020,2012,N825UA,ORD,21:47,21:55,107,94,8,21:50,5,0,0,0,0,0,SYR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69439,EV,11/20/2019,4103,N609UX,ORD,09:19,09:17,109,108,-2,09:10,7,0,0,0,0,0,SYR
69456,EV,11/24/2019,4461,N609UX,ORD,12:03,11:58,108,107,-5,11:54,4,0,0,0,0,0,SYR
69496,EV,12/11/2019,4063,N607UX,ORD,12:23,12:39,108,105,16,12:34,5,10,0,0,0,6,SYR
69500,EV,12/14/2019,4486,N612UX,ORD,09:04,08:53,109,109,-11,08:44,9,0,0,0,0,0,SYR
69502,EV,12/15/2019,4486,N616UX,ORD,12:23,12:51,108,116,28,12:46,5,15,0,8,0,5,SYR